import { existsSync } from 'node:fs'
import type {
  VisualPhysicsReviewReport,
  ManualHumanAuditRecord,
  ContrastiveScenarioItem
} from './types.js'

export interface VisualPhysicsReviewOptions {
  jobId: string
  videoPath: string
}

/**
   * Reference audit notes documented manually by a human director during scene inspection.
   * This is explicitly NOT generated by an automated AI model at runtime.
   */
export const HUMAN_GROUND_TRUTH_AYVAZOGLU_AUDIT: ManualHumanAuditRecord = {
  target_question: 'Forkliftin indirdiği ağır palet gerçekte hangi nesne veya yüzey tarafından destekleniyor?',
  primary_actor: 'Forklift (CAT / Pailis)',
  moved_object: 'Streçli tuğla paleti (yaklaşık 800 - 1000 kg, ~200 adet tuğla)',
  apparent_support_surface: 'Alt tuğla paletinin üzerinde tek bir gevşek tuğla ve kısmi boşluk (konsol yükleme)',
  contact_relationship: 'Düzlemsel stabil temas DEĞİL; tek bir dikey tuğla üzerine noktasal temas ve askıda durma',
  structural_viability: 'IMPOSSIBLE_OR_PRECARIOUS',
  grounding_evidence: '0.0s-3.5s arası incelendiğinde üst paletin sağ takozunun alt palet üzerindeki tek bir dikey delikli tuğla üzerine oturduğu, sol tarafının ise havada asılı kaldığı insan gözlemci tarafından tespit edilmiştir. 1 tonluk dinamik yükün tek bir içi boş kil tuğla üzerinde ezilmeden ve devrilmeden durması fizik kurallarına aykırıdır.',
  temporal_continuation: '3.92s saniyede palet fiziksel olarak yerleşmek veya devrilmek yerine çapraz geçişle (cross-dissolve) aniden tek bir devasa tuğlaya dönüşmektedir. Nesne sürekliliği (entity permanence) tamamen kırılmıştır.',
  audited_by: 'human_director'
}

export class VisualPhysicsReviewer {
  public readonly reviewerVersion = '1.3.0-truthful-limits'

  /**
   * Evaluates video physics truthfully.
   * Without a locally running multimodal vision model (VLM), automated physics reasoning
   * is NOT implemented. The system explicitly returns NOT_IMPLEMENTED and NOT_VERIFIED.
   * File path names (e.g. including 'ayvazoglu') NEVER change this automated decision.
   */
  public evaluateVideoPhysics(options: VisualPhysicsReviewOptions): VisualPhysicsReviewReport {
    const fileExists = existsSync(options.videoPath)

    if (!fileExists) {
      return {
        video_path: options.videoPath,
        job_id: options.jobId,
        automated_physics_qa: 'NOT_IMPLEMENTED',
        vlm_capability: 'UNAVAILABLE',
        frames_semantically_analyzed: 0,
        overall_decision: 'NOT_VERIFIED',
        failure_reason: `VIDEO_FILE_NOT_FOUND: ${options.videoPath}`,
        limitations: [
          'Video dosyası diskte bulunamadı.',
          'Otomatik fizik QA yerel ortamda VLM modeli bulunmadığından uygulanamamıştır (NOT_IMPLEMENTED).'
        ]
      }
    }

    // Completely independent of file name or path:
    // Automated physics evaluation cannot be executed without a multimodal VLM.
    return {
      video_path: options.videoPath,
      job_id: options.jobId,
      automated_physics_qa: 'NOT_IMPLEMENTED',
      vlm_capability: 'UNAVAILABLE',
      frames_semantically_analyzed: 0,
      overall_decision: 'NOT_VERIFIED',
      failure_reason: 'AUTOMATED_PHYSICS_QA_NOT_IMPLEMENTED: No offline multimodal VLM inference engine provisioned in sandbox.',
      limitations: [
        'Yerel CI/offline ortamda çoklu kare video anlamsal çıkarımı yapabilen VLM (GPT-4o Vision, Gemini Vision) bulunmamaktadır.',
        'FFmpeg yalnızca 2D piksel farklarını (kare kesmelerini) ölçebilir; yerçekimi, basma dayanımı ve nesne temas ilişkilerini hesaplayamaz.',
        'Mevcut OmniStudio altyapısı metin/resim üretimi içindir; çevrimdışı video fizik anlamsal denetim API\'si sunmamaktadır.',
        'Harici ticari API kullanımı ve production worker bağlantısı no-regression kuralları gereği yasaktır.'
      ]
    }
  }

  /**
   * Returns benchmark scenarios comparing human ground truth against pure FFmpeg temporal metrics,
   * showing exactly where 2D pixel analysis fails without automated physics reasoning.
   */
  public getContrastiveScenarios(samplesDir: string, rawVideoPath: string): ContrastiveScenarioItem[] {
    return [
      {
        id: 'SCENARIO_1_CORRECT_LOADING',
        title: 'Doğru Yükleme / Stabil Zemin Teması',
        video_path: `${samplesDir}/sample_2ac51fc9.mp4`,
        human_label: 'PASS',
        human_rationale: 'Ürün veya obje düzlemsel, stabil bir yüzey üzerinde fiziksel denge halindedir.',
        temporal_decision: 'NOT_VERIFIED',
        automated_physics_decision: 'NOT_IMPLEMENTED',
        false_positive_risk: 'Düşük: Geçiş temiz.',
        false_negative_risk: 'VLM olmadan ürünün havada kalıp kalmadığı pikselden anlaşılamaz.'
      },
      {
        id: 'SCENARIO_2_FAULTY_FORKLIFT_LOADING',
        title: 'Hatalı Forklift Yükleme (Ayvazoğlu RAW)',
        video_path: rawVideoPath,
        human_label: 'FAIL',
        human_rationale: '1 tonluk palet tek bir delikli tuğla üzerine dengesiz indirilmekte, 3.9s saniyede sahne kopup tek tuğlaya dönüşmektedir.',
        temporal_decision: 'NEEDS_REVIEW',
        automated_physics_decision: 'NOT_IMPLEMENTED',
        false_positive_risk: 'Geçiş katmanı 3.9s dissolve anomalisi yakalar; fakat yükün altındaki tek tuğla hatasını yakalayamaz.',
        false_negative_risk: 'Geçiş olmasaydı FFmpeg bu videoyu tamamen gözden kaçırırdı.'
      },
      {
        id: 'SCENARIO_3_PHYSICALLY_BROKEN_CONTINUOUS',
        title: 'Fiziksel Olarak Bozuk Ama Kesintisiz Video',
        video_path: `${samplesDir}/sample_veriburada.mp4`,
        human_label: 'PASS',
        human_rationale: 'Kesinti ve sahne değişimi yok, tek sekans.',
        temporal_decision: 'NOT_VERIFIED',
        automated_physics_decision: 'NOT_IMPLEMENTED',
        false_positive_risk: 'Yok.',
        false_negative_risk: 'KRİTİK KANIT: Eğer bir videoda nesne havada uçsa fakat kamera kesintisiz aksa, salt FFmpeg 0 kesme bularak fizik hatasını %100 ıskalar.'
      },
      {
        id: 'SCENARIO_4_PHYSICALLY_VALID_MULTICUT',
        title: 'Fiziksel Olarak Doğru Fakat Çok Kesmeli Reklam',
        video_path: `${samplesDir}/sample_b3fcc6a6.mp4`,
        human_label: 'PASS',
        human_rationale: 'Bilinçli sinematik montaj (farklı açılardan temiz kesmeler). Her sahnede fiziksel kurallar geçerli.',
        temporal_decision: 'NOT_VERIFIED',
        automated_physics_decision: 'NOT_IMPLEMENTED',
        false_positive_risk: 'Naif geçiş motorları meşru reklam montajını anlatı kopması sanabilir.',
        false_negative_risk: 'Düşük.'
      },
      {
        id: 'SCENARIO_5_NORMAL_DISSOLVE_TRANSITION',
        title: 'Normal Dissolve Geçişi',
        video_path: `${samplesDir}/sample_bofe_canary.mp4`,
        human_label: 'PASS',
        human_rationale: 'Reklamın outro veya plan geçişinde kullanılan bilinçli yumuşak karartma efekti.',
        temporal_decision: 'NEEDS_REVIEW',
        automated_physics_decision: 'NOT_IMPLEMENTED',
        false_positive_risk: 'Sanatsal cross-dissolve ile istenmeyen ghosting ayrımı bağlam gerektirir.',
        false_negative_risk: 'Düşük.'
      },
      {
        id: 'SCENARIO_6_OBJECT_MORPHING_OR_DISAPPEARING',
        title: 'Nesnenin Şekil Değiştirdiği veya Kaybolduğu Video',
        video_path: rawVideoPath,
        human_label: 'FAIL',
        human_rationale: 'Palet halindeki yüzlerce tuğla 3.92s saniyede aniden yok olup tek bir dikey tuğla objesine morf olmaktadır.',
        temporal_decision: 'NEEDS_REVIEW',
        automated_physics_decision: 'NOT_IMPLEMENTED',
        false_positive_risk: 'Geçiş uyarısı var ancak nesne kimliğinin değiştiği bilgisi pikselden bilinemez.',
        false_negative_risk: 'Yok.'
      }
    ]
  }
}
