import Link from 'next/link'
import { Card, CardHeader, PageHeader, QuietLink } from '@/components/ui'
import { Icon } from '@/components/icon'
export const metadata = { title: 'Yardım merkezi' }
const guides = [
  { icon: 'phone' as const, title: 'WhatsApp hattını bağlama', href: '/hesaplar', steps: ['WhatsApp hatları ekranında yeni bir hat oluşturun.', 'QR kodunu telefonunuzdaki Bağlı cihazlar bölümünden okutun veya telefon koduyla eşleştirin.', 'Durum “Bağlı” olduğunda hattınızı gönderim için seçebilirsiniz. Süresi dolan QR için yeniden bağlanın.'] },
  { icon: 'people' as const, title: 'Kişileri hazırlama', href: '/kisiler', steps: ['CSV yükleyin veya numaraları satır satır yapıştırın. İsim eklemek için numaradan sonra virgül kullanabilirsiniz.', 'Ülke kodu olmayan Türkiye numaraları +90 ile düzenlenir. Tekrarlanan numaralar ayıklanır.', 'Doğrulama için bağlı hat gerekir. WhatsApp kaydı iletişim izni yerine geçmez.'] },
  { icon: 'campaign' as const, title: 'Kampanya gönderme', href: '/kampanyalar', steps: ['Kampanya adını ve mesajı yazın; gerekirse görsel yükleyin.', 'Kişi listelerini ve gönderici hatları seçin. {{ad}} ifadesi kişi adıyla doldurulur.', 'Başlattıktan sonra gönderildi, atlandı ve başarısız sonuçlarını kampanya ayrıntısından izleyin. Duraklatma sürmekte olan tek mesajı geri almaz.'] },
  { icon: 'inbox' as const, title: 'Yanıtları yönetme', href: '/gelenler', steps: ['Gelen kutusunda bir konuşma seçin; tam geçmişi veya yalnız gelen mesajları görün.', 'Yanıtınızı yazıp gönderin. İşlem sıraya alınır; sonucu konuşmanın altında gösterilir.', 'İletişim istemeyen kişiyi kara listeye alın. Bu numara sonraki gönderimlerden çıkarılır.'] },
]
export default function HelpPage() {
  return <><PageHeader title="Yardım merkezi" description="İlk bağlantıdan günlük kullanıma, ihtiyacınız olan adımlar." /><div className="grid gap-5 lg:grid-cols-2">{guides.map(guide => <Card key={guide.title}><CardHeader title={<span className="flex items-center gap-3"><Icon name={guide.icon} className="text-accent" />{guide.title}</span>} /><ol className="space-y-4 p-5">{guide.steps.map((step, i) => <li key={step} className="flex gap-3 text-sm leading-relaxed text-ink-muted"><span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-canvas font-mono text-xs text-accent">{i + 1}</span><span>{step}</span></li>)}</ol><div className="px-5 pb-5"><QuietLink href={guide.href}>İlgili ekrana git →</QuietLink></div></Card>)}</div><div className="mt-8"><h2 className="mb-4 text-xl font-semibold">Bir şey beklediğiniz gibi çalışmıyor mu?</h2>{[['Gönderim kuyrukta bekliyor', 'Bağlı ve gönderime açık bir hat olduğunu kontrol edin. Günlük kota dolmuş, bekleme aralığı sürüyor veya servis geçici olarak yanıt vermiyor olabilir. Genel bakıştaki hat ve kuyruk durumuna bakın.'], ['Gönderim sonucu belirsiz', 'Bağlantı gönderim sırasında kesilmiş olabilir. Çift mesajı önlemek için otomatik tekrar yapılmaz. Yeniden göndermeden önce telefonunuzdaki konuşmayı kontrol edin.'], ['Şifremi unuttum', 'Giriş ekranındaki “Şifremi unuttum” bağlantısıyla e-posta isteyin. Bağlantıyı aynı tarayıcıda açın. Spam klasörünü kontrol edin; eski bağlantı yerine en son gönderileni kullanın.'], ['Görsel veya metin üretimi açık değil', 'Yapay zekâ özellikleri sunucu yapılandırmasına bağlıdır. Ayarlar’dan kullanılabilir özellikleri kontrol edin. Marka şablonları ve kendi görselinizi yükleme ayrı seçeneklerdir.']].map(([q, a]) => <details key={q} className="border-b border-hairline"><summary className="cursor-pointer py-4 font-medium">{q}</summary><p className="max-w-3xl pb-5 text-sm leading-relaxed text-ink-muted">{a}</p></details>)}<p className="mt-6 text-sm text-ink-muted">Sorun sürerse işletmenizin destek sorumlusuna ilgili ekranı, işlem zamanını ve varsa hata kodunu iletin. <Link href="/durum" className="text-accent underline">Genel bakışı açın.</Link></p></div></>
}
