// Generated by Supabase MCP generate_typescript_types
// Do not edit manually — regenerate from the project schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      account_events: {
        Row: {
          account_id: string | null
          created_at: string
          created_by: string
          detail: Json
          event: string
          id: number
          level: string
          org_id: string
        }
        Insert: {
          account_id?: string | null
          created_at?: string
          created_by: string
          detail?: Json
          event: string
          id?: never
          level?: string
          org_id: string
        }
        Update: {
          account_id?: string | null
          created_at?: string
          created_by?: string
          detail?: Json
          event?: string
          id?: never
          level?: string
          org_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "account_events_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "account_events_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      accounts: {
        Row: {
          connected_at: string | null
          created_at: string
          created_by: string
          daily_send_limit: number
          enabled: boolean
          id: string
          is_locked: boolean
          label: string
          last_disconnect_code: number | null
          last_seen_at: string | null
          lock_reason: string | null
          locked_at: string | null
          new_chat_quota_cycle_end: string | null
          new_chat_quota_total: number | null
          new_chat_quota_used: number | null
          org_id: string
          pairing_code: string | null
          pairing_expires_at: string | null
          phone_e164: string | null
          qr_code: string | null
          qr_expires_at: string | null
          reachout_lock_type: string | null
          reachout_locked_until: string | null
          schema_version: number
          sent_today: number
          sent_today_on: string | null
          status: string
          status_detail: string | null
          updated_at: string
          wa_jid: string | null
          wa_lid: string | null
          wa_version: string | null
          warmup_started_at: string | null
        }
        Insert: {
          connected_at?: string | null
          created_at?: string
          created_by: string
          daily_send_limit?: number
          enabled?: boolean
          id?: string
          is_locked?: boolean
          label: string
          last_disconnect_code?: number | null
          last_seen_at?: string | null
          lock_reason?: string | null
          locked_at?: string | null
          new_chat_quota_cycle_end?: string | null
          new_chat_quota_total?: number | null
          new_chat_quota_used?: number | null
          org_id: string
          pairing_code?: string | null
          pairing_expires_at?: string | null
          phone_e164?: string | null
          qr_code?: string | null
          qr_expires_at?: string | null
          reachout_lock_type?: string | null
          reachout_locked_until?: string | null
          schema_version?: number
          sent_today?: number
          sent_today_on?: string | null
          status?: string
          status_detail?: string | null
          updated_at?: string
          wa_jid?: string | null
          wa_lid?: string | null
          wa_version?: string | null
          warmup_started_at?: string | null
        }
        Update: {
          connected_at?: string | null
          created_at?: string
          created_by?: string
          daily_send_limit?: number
          enabled?: boolean
          id?: string
          is_locked?: boolean
          label?: string
          last_disconnect_code?: number | null
          last_seen_at?: string | null
          lock_reason?: string | null
          locked_at?: string | null
          new_chat_quota_cycle_end?: string | null
          new_chat_quota_total?: number | null
          new_chat_quota_used?: number | null
          org_id?: string
          pairing_code?: string | null
          pairing_expires_at?: string | null
          phone_e164?: string | null
          qr_code?: string | null
          qr_expires_at?: string | null
          reachout_lock_type?: string | null
          reachout_locked_until?: string | null
          schema_version?: number
          sent_today?: number
          sent_today_on?: string | null
          status?: string
          status_detail?: string | null
          updated_at?: string
          wa_jid?: string | null
          wa_lid?: string | null
          wa_version?: string | null
          warmup_started_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "accounts_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      blacklist: {
        Row: {
          created_at: string
          created_by: string
          id: string
          org_id: string
          phone_e164: string
          reason: string | null
        }
        Insert: {
          created_at?: string
          created_by: string
          id?: string
          org_id: string
          phone_e164: string
          reason?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string
          id?: string
          org_id?: string
          phone_e164?: string
          reason?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "blacklist_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      brand_kits: {
        Row: {
          colors: Json
          created_at: string
          created_by: string
          fonts: Json
          id: string
          is_default: boolean
          logo_path: string | null
          name: string
          org_id: string
          tone: string | null
          updated_at: string
        }
        Insert: {
          colors?: Json
          created_at?: string
          created_by: string
          fonts?: Json
          id?: string
          is_default?: boolean
          logo_path?: string | null
          name: string
          org_id: string
          tone?: string | null
          updated_at?: string
        }
        Update: {
          colors?: Json
          created_at?: string
          created_by?: string
          fonts?: Json
          id?: string
          is_default?: boolean
          logo_path?: string | null
          name?: string
          org_id?: string
          tone?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "brand_kits_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      campaign_accounts: {
        Row: {
          account_id: string
          campaign_id: string
          created_by: string
          org_id: string
          sent_count: number
        }
        Insert: {
          account_id: string
          campaign_id: string
          created_by: string
          org_id: string
          sent_count?: number
        }
        Update: {
          account_id?: string
          campaign_id?: string
          created_by?: string
          org_id?: string
          sent_count?: number
        }
        Relationships: [
          {
            foreignKeyName: "campaign_accounts_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaign_accounts_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaign_accounts_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      campaign_targets: {
        Row: {
          account_id: string | null
          attempts: number
          campaign_id: string
          contact_id: string | null
          created_at: string
          created_by: string
          delivery_attempted: boolean
          error: string | null
          id: number
          org_id: string
          personalized_body: string | null
          phone_e164: string
          scheduled_for: string | null
          sent_at: string | null
          status: string
          updated_at: string
          wa_message_id: string | null
        }
        Insert: {
          account_id?: string | null
          attempts?: number
          campaign_id: string
          contact_id?: string | null
          created_at?: string
          created_by: string
          delivery_attempted?: boolean
          error?: string | null
          id?: never
          org_id: string
          personalized_body?: string | null
          phone_e164: string
          scheduled_for?: string | null
          sent_at?: string | null
          status?: string
          updated_at?: string
          wa_message_id?: string | null
        }
        Update: {
          account_id?: string | null
          attempts?: number
          campaign_id?: string
          contact_id?: string | null
          created_at?: string
          created_by?: string
          delivery_attempted?: boolean
          error?: string | null
          id?: never
          org_id?: string
          personalized_body?: string | null
          phone_e164?: string
          scheduled_for?: string | null
          sent_at?: string | null
          status?: string
          updated_at?: string
          wa_message_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "campaign_targets_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaign_targets_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaign_targets_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaign_targets_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      campaigns: {
        Row: {
          ab_percent: number
          body: string | null
          body_b: string | null
          completed_at: string | null
          created_at: string
          created_by: string
          creative_id: string | null
          daily_cap_per_account: number
          failed_count: number
          id: string
          max_delay_seconds: number
          media_mime: string | null
          media_url: string | null
          message_type: string
          min_delay_seconds: number
          name: string
          org_id: string
          paused_at: string | null
          scheduled_at: string | null
          sent_count: number
          skipped_count: number
          source_list_ids: string[]
          started_at: string | null
          status: string
          stop_reason: string | null
          total_targets: number
          updated_at: string
        }
        Insert: {
          ab_percent?: number
          body?: string | null
          body_b?: string | null
          completed_at?: string | null
          created_at?: string
          created_by: string
          creative_id?: string | null
          daily_cap_per_account?: number
          failed_count?: number
          id?: string
          max_delay_seconds?: number
          media_mime?: string | null
          media_url?: string | null
          message_type?: string
          min_delay_seconds?: number
          name: string
          org_id: string
          paused_at?: string | null
          scheduled_at?: string | null
          sent_count?: number
          skipped_count?: number
          source_list_ids?: string[]
          started_at?: string | null
          status?: string
          stop_reason?: string | null
          total_targets?: number
          updated_at?: string
        }
        Update: {
          ab_percent?: number
          body?: string | null
          body_b?: string | null
          completed_at?: string | null
          created_at?: string
          created_by?: string
          creative_id?: string | null
          daily_cap_per_account?: number
          failed_count?: number
          id?: string
          max_delay_seconds?: number
          media_mime?: string | null
          media_url?: string | null
          message_type?: string
          min_delay_seconds?: number
          name?: string
          org_id?: string
          paused_at?: string | null
          scheduled_at?: string | null
          sent_count?: number
          skipped_count?: number
          source_list_ids?: string[]
          started_at?: string | null
          status?: string
          stop_reason?: string | null
          total_targets?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "campaigns_creative_id_fkey"
            columns: ["creative_id"]
            isOneToOne: false
            referencedRelation: "creatives"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaigns_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      contact_list_members: {
        Row: {
          added_at: string
          contact_id: string
          created_by: string
          list_id: string
          org_id: string
        }
        Insert: {
          added_at?: string
          contact_id: string
          created_by: string
          list_id: string
          org_id: string
        }
        Update: {
          added_at?: string
          contact_id?: string
          created_by?: string
          list_id?: string
          org_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "contact_list_members_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contact_list_members_list_id_fkey"
            columns: ["list_id"]
            isOneToOne: false
            referencedRelation: "contact_lists"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contact_list_members_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      contact_lists: {
        Row: {
          contact_count: number
          created_at: string
          created_by: string
          description: string | null
          id: string
          name: string
          org_id: string
          source: string
          updated_at: string
        }
        Insert: {
          contact_count?: number
          created_at?: string
          created_by: string
          description?: string | null
          id?: string
          name: string
          org_id: string
          source?: string
          updated_at?: string
        }
        Update: {
          contact_count?: number
          created_at?: string
          created_by?: string
          description?: string | null
          id?: string
          name?: string
          org_id?: string
          source?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "contact_lists_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      contacts: {
        Row: {
          created_at: string
          created_by: string
          extra: Json
          id: string
          name: string | null
          org_id: string
          phone_e164: string
          source: string
          updated_at: string
          wa_checked_at: string | null
          wa_jid: string | null
          wa_status: string
        }
        Insert: {
          created_at?: string
          created_by: string
          extra?: Json
          id?: string
          name?: string | null
          org_id: string
          phone_e164: string
          source?: string
          updated_at?: string
          wa_checked_at?: string | null
          wa_jid?: string | null
          wa_status?: string
        }
        Update: {
          created_at?: string
          created_by?: string
          extra?: Json
          id?: string
          name?: string | null
          org_id?: string
          phone_e164?: string
          source?: string
          updated_at?: string
          wa_checked_at?: string | null
          wa_jid?: string | null
          wa_status?: string
        }
        Relationships: [
          {
            foreignKeyName: "contacts_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      creatives: {
        Row: {
          brand_kit_id: string | null
          created_at: string
          created_by: string
          error: string | null
          format: string
          height: number | null
          id: string
          org_id: string
          payload: Json
          public_url: string | null
          status: string
          storage_path: string | null
          template: string
          updated_at: string
          width: number | null
        }
        Insert: {
          brand_kit_id?: string | null
          created_at?: string
          created_by: string
          error?: string | null
          format?: string
          height?: number | null
          id?: string
          org_id: string
          payload?: Json
          public_url?: string | null
          status?: string
          storage_path?: string | null
          template?: string
          updated_at?: string
          width?: number | null
        }
        Update: {
          brand_kit_id?: string | null
          created_at?: string
          created_by?: string
          error?: string | null
          format?: string
          height?: number | null
          id?: string
          org_id?: string
          payload?: Json
          public_url?: string | null
          status?: string
          storage_path?: string | null
          template?: string
          updated_at?: string
          width?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "creatives_brand_kit_id_fkey"
            columns: ["brand_kit_id"]
            isOneToOne: false
            referencedRelation: "brand_kits"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "creatives_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      jobs: {
        Row: {
          account_id: string | null
          attempts: number
          campaign_id: string | null
          claimed_at: string | null
          claimed_by: string | null
          created_at: string
          created_by: string | null
          error: string | null
          finished_at: string | null
          id: number
          max_attempts: number
          org_id: string | null
          payload: Json
          priority: number
          result: Json | null
          run_after: string
          status: string
          type: string
          updated_at: string
        }
        Insert: {
          account_id?: string | null
          attempts?: number
          campaign_id?: string | null
          claimed_at?: string | null
          claimed_by?: string | null
          created_at?: string
          created_by?: string | null
          error?: string | null
          finished_at?: string | null
          id?: never
          max_attempts?: number
          org_id?: string | null
          payload?: Json
          priority?: number
          result?: Json | null
          run_after?: string
          status?: string
          type: string
          updated_at?: string
        }
        Update: {
          account_id?: string | null
          attempts?: number
          campaign_id?: string | null
          claimed_at?: string | null
          claimed_by?: string | null
          created_at?: string
          created_by?: string | null
          error?: string | null
          finished_at?: string | null
          id?: never
          max_attempts?: number
          org_id?: string | null
          payload?: Json
          priority?: number
          result?: Json | null
          run_after?: string
          status?: string
          type?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "jobs_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      message_log: {
        Row: {
          account_id: string | null
          body: string | null
          campaign_id: string | null
          created_at: string
          created_by: string
          direction: string
          error: string | null
          id: number
          media_url: string | null
          message_type: string
          org_id: string
          phone_e164: string | null
          remote_jid: string | null
          status: string
          wa_message_id: string | null
        }
        Insert: {
          account_id?: string | null
          body?: string | null
          campaign_id?: string | null
          created_at?: string
          created_by: string
          direction?: string
          error?: string | null
          id?: never
          media_url?: string | null
          message_type?: string
          org_id: string
          phone_e164?: string | null
          remote_jid?: string | null
          status?: string
          wa_message_id?: string | null
        }
        Update: {
          account_id?: string | null
          body?: string | null
          campaign_id?: string | null
          created_at?: string
          created_by?: string
          direction?: string
          error?: string | null
          id?: never
          media_url?: string | null
          message_type?: string
          org_id?: string
          phone_e164?: string | null
          remote_jid?: string | null
          status?: string
          wa_message_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "message_log_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "message_log_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "message_log_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      organization_members: {
        Row: {
          created_at: string
          org_id: string
          role: string
          user_id: string
        }
        Insert: {
          created_at?: string
          org_id: string
          role?: string
          user_id: string
        }
        Update: {
          created_at?: string
          org_id?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "organization_members_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          accounts_quota: number
          created_at: string
          id: string
          monthly_message_quota: number
          name: string
          plan: string
          slug: string
          updated_at: string
        }
        Insert: {
          accounts_quota?: number
          created_at?: string
          id?: string
          monthly_message_quota?: number
          name: string
          plan?: string
          slug: string
          updated_at?: string
        }
        Update: {
          accounts_quota?: number
          created_at?: string
          id?: string
          monthly_message_quota?: number
          name?: string
          plan?: string
          slug?: string
          updated_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          accounts_quota: number
          active_org_id: string | null
          company: string | null
          created_at: string
          email: string | null
          full_name: string | null
          id: string
          monthly_message_quota: number
          onboarded_at: string | null
          onboarding_step: string
          plan: string
          updated_at: string
        }
        Insert: {
          accounts_quota?: number
          active_org_id?: string | null
          company?: string | null
          created_at?: string
          email?: string | null
          full_name?: string | null
          id: string
          monthly_message_quota?: number
          onboarded_at?: string | null
          onboarding_step?: string
          plan?: string
          updated_at?: string
        }
        Update: {
          accounts_quota?: number
          active_org_id?: string | null
          company?: string | null
          created_at?: string
          email?: string | null
          full_name?: string | null
          id?: string
          monthly_message_quota?: number
          onboarded_at?: string | null
          onboarding_step?: string
          plan?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_active_org_id_fkey"
            columns: ["active_org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      add_organization_member: {
        Args: { p_email: string; p_org_id: string; p_role?: string }
        Returns: undefined
      }
      set_organization_member_role: {
        Args: { p_org_id: string; p_role: string; p_user_id: string }
        Returns: undefined
      }
      create_organization: { Args: { p_name: string }; Returns: string }
      is_org_admin: { Args: { p_org_id: string }; Returns: boolean }
      is_org_member: { Args: { p_org_id: string }; Returns: boolean }
      slugify: { Args: { p_text: string }; Returns: string }
      user_org_ids: { Args: never; Returns: string[] }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
