/**
 * MESAJIFY CREATIVE STUDIO — CREATIVE ARCHETYPE LIBRARY
 *
 * 20 Curated Commercial Art-Direction Archetypes.
 * Each defines concrete, professional composition and design grammar — not mere adjectives.
 */

export interface ArchetypeGrammar {
  id: string
  name: string
  description: string
  composition: {
    grid: string
    focalPoint: string
    productScale: string
    productPosition: string
    humanPosition: string
    negativeSpace: string
    cropStrategy: string
    cameraAngle: string
    depthLayers: string[]
  }
  artDirection: {
    visualLanguage: string
    materialLanguage: string
    lighting: string
    backgroundTreatment: string
    colorTreatment: string
    contrastStrategy: string
    texture: string
    atmosphere: string
  }
  graphicLanguage: {
    shapes: string[]
    frames: string[]
    lines: string[]
    panels: string[]
    glow: string
    grain: string
    decorativeMotifs: string[]
  }
  typographyDirection: {
    headlineCharacter: string
    hierarchy: string
    alignment: string
    density: string
    styleFeel: string
  }
  bestForObjectives: string[]
  antiGenericRules: string[]
}

export const CREATIVE_ARCHETYPES: Record<string, ArchetypeGrammar> = {
  EDITORIAL_LUXURY: {
    id: 'EDITORIAL_LUXURY',
    name: 'Editorial Luxury',
    description: 'Vogue/Monocle aesthetic with deliberate negative space, raking light, and bespoke material surfaces.',
    composition: {
      grid: 'Golden ratio 60/40 asymmetrical split with expansive editorial margins',
      focalPoint: 'Off-center lower-right product placement anchored by deep architectural shadow',
      productScale: 'Hero product occupies 35-45% of canvas height, impeccably proportioned',
      productPosition: 'Resting on honed natural travertine or matte limestone slab',
      humanPosition: 'Optional: Elegantly styled hands or partial profile in soft out-of-focus background layer',
      negativeSpace: 'Generous 35% negative space reserved for high-contrast typography hierarchy',
      cropStrategy: 'Medium-close crop preserving full product envelope with breathing room',
      cameraAngle: 'Low eye-level (15 degrees elevation) producing regal presence',
      depthLayers: ['Sharp crisp foreground surface', 'In-focus hero product', 'Subtle architectural raking shadow', 'Atmospheric soft backdrop'],
    },
    artDirection: {
      visualLanguage: 'Restrained elegance, tactile luxury, bespoke craftsmanship',
      materialLanguage: 'Honed travertine, raw linen, brushed warm brass, matte ceramic',
      lighting: 'Single large diffused softbox from 45-degree angle with crisp directional rim highlight',
      backgroundTreatment: 'Subtle plaster wall texture with architectural window shadow pattern (gobos)',
      colorTreatment: 'Monochromatic warm neutrals with brand accent confined to key details',
      contrastStrategy: 'Subtle mid-tone contrast with deep velvety shadows and restrained highlights',
      texture: 'Micro-tactile stone grain and matte paper textures',
      atmosphere: 'Quiet, premium, aspirational, bespoke interior studio ambiance',
    },
    graphicLanguage: {
      shapes: ['Slender hairline borders', 'Minimal rectangular boundary frames'],
      frames: ['1px razor-sharp boundary inset 40px from canvas edge'],
      lines: ['Ultra-fine horizontal rule dividing brand identity from headline'],
      panels: ['Translucent warm-grey panel backing secondary details'],
      glow: 'Zero artificial glow, strictly organic optical lens bloom on specular edges',
      grain: 'Subtle 2% 35mm photographic film grain for organic warmth',
      decorativeMotifs: ['Minimalist serif numeral index', 'Small typographic coordinates'],
    },
    typographyDirection: {
      headlineCharacter: 'High-contrast modern serif with refined editorial tracking',
      hierarchy: 'Hero editorial headline dominant, followed by whisper-quiet serif supporting text',
      alignment: 'Flushed left, ragged right in the designated negative space quadrant',
      density: 'Low density, high impact whitespace breathing room',
      styleFeel: 'Haute couture, architectural monograph, European luxury publication',
    },
    bestForObjectives: ['BRAND_AWARENESS', 'NEW_PRODUCT', 'PREMIUM'],
    antiGenericRules: [
      'No tacky glossy spheres or floating sparkles',
      'No centered floating product on pure white or generic gradient',
      'No neon colors or saturated plastic textures',
    ],
  },

  BOLD_RETAIL: {
    id: 'BOLD_RETAIL',
    name: 'Bold Retail',
    description: 'High-energy commercial retail campaign with decisive framing, punchy color blocks, and urgent clarity.',
    composition: {
      grid: 'Dynamic diagonal thirds grid with strong diagonal energy vectors',
      focalPoint: 'Dominant hero product breaking the upper-middle frame',
      productScale: 'Product commands 55-65% of the frame with massive presence',
      productPosition: 'Dynamic forward tilt at 8 degrees, angled toward viewer',
      humanPosition: 'Energetic lifestyle talent interacting directly with product',
      negativeSpace: 'Dedicated 25% upper or lower banner channel for promotional offer headline',
      cropStrategy: 'Tight, confident hero crop emphasizing packaging details and craftsmanship',
      cameraAngle: 'Slightly low Dutch angle (5 degrees) instilling dynamism',
      depthLayers: ['Promotional offer overlay badge', 'Hero product in razor-sharp focus', 'Contrasting geometric backdrop', 'Dynamic motion shadow'],
    },
    artDirection: {
      visualLanguage: 'Decisive, punchy, high-conversion commercial retail impact',
      materialLanguage: 'High-gloss acrylic, powder-coated steel, saturated matte studio surfaces',
      lighting: 'Bright 3-point commercial studio lighting with crisp edge separation',
      backgroundTreatment: 'Bold two-tone architectural color blocking with razor-sharp geometric division',
      colorTreatment: 'Vivid high-contrast brand palette with striking accent pop for offer elements',
      contrastStrategy: 'Punchy commercial contrast, crisp whites, pure deep blacks',
      texture: 'Clean polished surfaces with tactile product realism',
      atmosphere: 'Fast-paced, trustworthy, instant commercial purchase desire',
    },
    graphicLanguage: {
      shapes: ['Geometric angled badges', 'Bold price tags', 'Clean pill capsules'],
      frames: ['Thick 3px high-contrast perimeter accent accents'],
      lines: ['Bold diagonal divider lines directing eyes to CTA'],
      panels: ['Solid high-contrast accent blocks highlighting pricing & delivery'],
      glow: 'Subtle rim luminescence separating product from backdrop',
      grain: 'Crisp digital zero-noise commercial sharpness',
      decorativeMotifs: ['Bold percentage tags', 'Verified authentic checkmarks'],
    },
    typographyDirection: {
      headlineCharacter: 'Heavyweight condensed grotesque sans-serif with tight letterspacing',
      hierarchy: 'Direct, punchy headline paired with high-visibility offer value',
      alignment: 'Centered or strong left-aligned block with solid horizontal grounding',
      density: 'Medium density, maximum legibility on mobile feeds',
      styleFeel: 'Flagship retail launch, seasonal blockbuster campaign',
    },
    bestForObjectives: ['SALES_OFFER', 'CAMPAIGN', 'DYNAMIC_OFFER'],
    antiGenericRules: [
      'No tacky 90s supermarket cartoon starbursts',
      'No blurry compression artifacts or cheap clip-art icons',
      'No ambiguous product silhouettes',
    ],
  },

  CINEMATIC_PRODUCT_HERO: {
    id: 'CINEMATIC_PRODUCT_HERO',
    name: 'Cinematic Product Hero',
    description: 'Anamorphic film lighting, atmospheric particulate, deep cinematic bokeh, and epic scale.',
    composition: {
      grid: 'Central cinematic symmetry balanced by volumetric atmospheric depth',
      focalPoint: 'Product anchored perfectly in the sweet spot of anamorphic depth of field',
      productScale: 'Prominent 50% vertical presence with dramatic vertical breathing space',
      productPosition: 'Resting on textured wet slate, rugged rock, or brushed industrial platform',
      humanPosition: 'Silhouette or atmospheric background observer adding scale',
      negativeSpace: 'Cinematic upper letterbox zone perfectly graded for title copy',
      cropStrategy: 'Epic wide-lens medium close-up with dramatic perspective falloff',
      cameraAngle: 'Ground-level worm eye view (25 degrees upward) magnifying stature',
      depthLayers: ['Foreground atmospheric particles/mist', 'Ultra-sharp hero subject', 'Backlit specular rim light', 'Deep moody textured horizon'],
    },
    artDirection: {
      visualLanguage: 'Cinematic trailer still, epic blockbuster commercial cinematography',
      materialLanguage: 'Wet obsidian, rugged basalt, weathered titanium, brushed steel',
      lighting: 'Dramatic 10:1 high-contrast cross-key lighting with anamorphic lens flare and strong backlight',
      backgroundTreatment: 'Moody cinematic horizon with volumetric atmospheric haze or light fog',
      colorTreatment: 'Teal-and-orange cinematic color split or rich monochrome with gold speculars',
      contrastStrategy: 'Heavy cinematic shadow falloff with specular peak highlights',
      texture: 'Hyper-detailed surface reflections, condensation droplets, or atmospheric dust motes',
      atmosphere: 'Epic, mysterious, legendary, momentous commercial reveal',
    },
    graphicLanguage: {
      shapes: ['Anamorphic widescreen bar guides', 'Subtle technical reticles'],
      frames: ['Minimal letterbox cinematic borders'],
      lines: ['Fine cinematic calibration lines at frame corners'],
      panels: ['Dark gradient vignetting ensuring text readability'],
      glow: 'Authentic anamorphic streak bloom and optical halation',
      grain: 'Fine 16mm organic motion-picture film grain',
      decorativeMotifs: ['Minimal aspect ratio indicator', 'Scene technical coordinates'],
    },
    typographyDirection: {
      headlineCharacter: 'Wide-tracked all-caps modern sans-serif with cinematic gravity',
      hierarchy: 'Monolithic single-line headline with understated premium subheading',
      alignment: 'Center aligned or bottom-left anchored like a feature film title card',
      density: 'Minimal density, maximum visual tension',
      styleFeel: 'Cinematic masterpiece title, Apple product keynote reveal',
    },
    bestForObjectives: ['NEW_PRODUCT', 'PRODUCT_HERO', 'BRAND_AWARENESS'],
    antiGenericRules: [
      'No flat 2D vector clip-art superimposed on 3D scene',
      'No generic pastel colors',
      'No floating cartoon arrows or emojis',
    ],
  },

  PREMIUM_MONOCHROME: {
    id: 'PREMIUM_MONOCHROME',
    name: 'Premium Monochrome',
    description: 'Exquisite single-hue tonal palette where the product or brand accent provides the single decisive focal rupture.',
    composition: {
      grid: 'Strict minimalist Swiss grid with modular mathematical proportions',
      focalPoint: 'The single chromatic accent in an otherwise disciplined tonal canvas',
      productScale: 'Medium 40% scale allowing negative space to project authority',
      productPosition: 'Flawlessly leveled on a monochromatic stepped pedestal',
      humanPosition: 'None or monochromatic sculptural mannequin form',
      negativeSpace: '50% immaculate tonal negative space',
      cropStrategy: 'Balanced centered or golden-third placement with generous borders',
      cameraAngle: 'Direct straight-on architectural elevation (0 degrees)',
      depthLayers: ['Micro foreground shadow', 'Sculptural product', 'Graduated tonal wall', 'Soft architectural ambient shadow'],
    },
    artDirection: {
      visualLanguage: 'Architectural minimalism, Bauhaus discipline, Scandinavian poise',
      materialLanguage: 'Cast concrete, matte anodized aluminum, sandblasted glass, felt',
      lighting: 'Overhead diffused skylight with ultra-soft directional wrap',
      backgroundTreatment: 'Seamless graduated monochromatic studio cove',
      colorTreatment: '90% charcoal/slate/ivory tonal gradient + 10% pure brand accent color',
      contrastStrategy: 'Delicate tonal gradations with surgical micro-contrast',
      texture: 'Fine tactile micro-textures: matte powder-coat, brushed grain',
      atmosphere: 'Serene, intellectual, authoritative, timeless luxury',
    },
    graphicLanguage: {
      shapes: ['Pure Euclidean circles and rectangles', 'Precision architectural notches'],
      frames: ['Swiss grid alignment guides and outer hairline box'],
      lines: ['Precision rule lines separating modular content blocks'],
      panels: ['Frosted acrylic floating panels with subtle backdrop blur'],
      glow: 'Zero glow, total matte purity',
      grain: 'Fine velvety paper texture',
      decorativeMotifs: ['Grid index numbers (01, 02)', 'Subtle alignment crosshairs'],
    },
    typographyDirection: {
      headlineCharacter: 'Immaculately kerned neo-grotesque (Akzidenz/Helvetica Neue/Inter style)',
      hierarchy: 'Structured architectural hierarchy with rigorous mathematical scale steps',
      alignment: 'Flush left along the strict Swiss grid line',
      density: 'Spacious, methodical, clinical confidence',
      styleFeel: 'Swiss design biennial, Braun design monograph, Leica campaign',
    },
    bestForObjectives: ['BRAND_AWARENESS', 'PREMIUM'],
    antiGenericRules: [
      'No multi-color rainbow gradients',
      'No chaotic unaligned elements',
      'No generic festive clip-art',
    ],
  },

  HIGH_ENERGY_PERFORMANCE: {
    id: 'HIGH_ENERGY_PERFORMANCE',
    name: 'High Energy Performance',
    description: 'Kinetic dynamism, diagonal velocity lines, explosive physical splash/dust, and unstoppable momentum.',
    composition: {
      grid: 'Aggressive 30-degree diagonal shear grid with kinetic forward vectors',
      focalPoint: 'Product captured in mid-action or dynamic levitation with explosive splash/debris',
      productScale: 'Product dominates 60% of canvas with explosive outward energy',
      productPosition: 'Dynamic mid-air angle (18 degrees tilt) breaking through visual planes',
      humanPosition: 'High-performance athlete or specialist captured in peak athletic action',
      negativeSpace: 'Dynamic corner negative spaces channeling eye movement into headline and CTA',
      cropStrategy: 'Aggressive dynamic crop with edge cutoffs implying immense scale',
      cameraAngle: 'High-speed action camera angle with exaggerated perspective lens',
      depthLayers: ['Foreground velocity splash/particles', 'Razor-sharp frozen product', 'Midground kinetic shockwave', 'High-contrast radial motion backdrop'],
    },
    artDirection: {
      visualLanguage: 'Kinetic power, peak physical performance, relentless drive',
      materialLanguage: 'Carbon fiber, vulcanized rubber, ripstop nylon, forged composite',
      lighting: 'High-speed strobe lighting (1/8000s freeze) with intense dual-color rim lighting',
      backgroundTreatment: 'Shattered surface, kinetic water spray, dust cloud, or industrial arena',
      colorTreatment: 'High-voltage electric brand accents contrasting against deep asphalt darks',
      contrastStrategy: 'Maximum high-energy contrast, zero muted midtones',
      texture: 'Frozen water droplets, carbon weave, gravel particles, athletic sweat',
      atmosphere: 'Electrifying, intense, adrenaline-fueled, uncompromising power',
    },
    graphicLanguage: {
      shapes: ['Angled chevron badges', 'Velocity wedges', 'Speed trails'],
      frames: ['Dynamic slashed corner frames'],
      lines: ['Double diagonal speed stripes along velocity vectors'],
      panels: ['Angled high-visibility data badges for specs and numbers'],
      glow: 'High-intensity directional laser neon edge luminescence',
      grain: 'Raw energetic digital sports photography grit',
      decorativeMotifs: ['Telemetry data indicators', 'Performance index icons'],
    },
    typographyDirection: {
      headlineCharacter: 'Ultra-bold forward-slanted technical grotesque with massive visual weight',
      hierarchy: 'Explosive punchline headline followed by high-speed bullet specs',
      alignment: 'Slanted forward or stacked aggressively with tight line height',
      density: 'High energy, rapid visual absorption in 0.8 seconds',
      styleFeel: 'Nike/Red Bull extreme sports launch, Formula 1 performance poster',
    },
    bestForObjectives: ['SALES_OFFER', 'DYNAMIC_OFFER', 'PRODUCT_HERO'],
    antiGenericRules: [
      'No static boring centered product',
      'No soft dreamy pastel tones',
      'No sleepy decorative flourishes',
    ],
  },

  MODERN_TECH_GLASS: {
    id: 'MODERN_TECH_GLASS',
    name: 'Modern Tech Glass',
    description: 'Frosted glassmorphism, iridescent reflections, glowing data vectors, and clean Silicon Valley precision.',
    composition: {
      grid: 'Modern digital viewport grid with floating UI card planes',
      focalPoint: 'Product or digital interface hovering gracefully above layered frosted glass planes',
      productScale: 'Balanced 45-50% scale integrated harmoniously with floating interface planes',
      productPosition: 'Zero-gravity floating levitation with subtle ambient light reflection below',
      humanPosition: 'Focused professional interacting with transparent digital surface',
      negativeSpace: 'Clean airy negative space on left or top for software headline copy',
      cropStrategy: 'Three-quarter isometric or frontal floating showcase',
      cameraAngle: 'Elevated 20-degree isometric perspective showcasing multi-layer depth',
      depthLayers: ['Foreground floating glass tag', 'Primary hero product / hardware', 'Translucent UI interface plane', 'Deep dark gradient background with subtle network grid'],
    },
    artDirection: {
      visualLanguage: 'Next-generation software, frictionless cloud technology, pure optical clarity',
      materialLanguage: 'Frosted silica glass, iridescent optical coatings, matte anodized space grey',
      lighting: 'Internal subsurface scattering glow combined with precision directional edge lights',
      backgroundTreatment: 'Deep rich dark-mode gradient with ultra-subtle optical refraction grid',
      colorTreatment: 'Cyan, violet, emerald glow accents on deep charcoal backdrop',
      contrastStrategy: 'Luminous light-emitting elements contrasting against rich dark field',
      texture: 'Silky smooth anti-reflective glass, precision laser-etched micro-dots',
      atmosphere: 'Intelligent, frictionless, advanced, state-of-the-art innovation',
    },
    graphicLanguage: {
      shapes: ['Floating rounded-rectangle glass panels', 'Data pills', 'Status badges'],
      frames: ['Subtle 1px glass border with 20% opacity gradient stroke'],
      lines: ['Fine glowing network connector lines and circuit traces'],
      panels: ['Backdrop-filtered frosted glass cards with specular highlight border'],
      glow: 'Controlled soft ambient glow behind key interactive elements',
      grain: 'Zero grain, pristine vector optical sharpness',
      decorativeMotifs: ['Real-time status indicators', 'Latency/speed benchmark tags'],
    },
    typographyDirection: {
      headlineCharacter: 'Crisp geometric modern sans-serif (SF Pro / Inter / Geist style)',
      hierarchy: 'Clean modular headline paired with metric data callouts and clean CTA',
      alignment: 'Left aligned within the primary glass panel zone',
      density: 'Balanced, highly scannable, mobile dashboard aesthetic',
      styleFeel: 'Linear / Stripe / Vercel product release, Apple Vision Pro OS',
    },
    bestForObjectives: ['NEW_PRODUCT', 'BRAND_AWARENESS'],
    antiGenericRules: [
      'No cheesy 90s binary code matrices (010101)',
      'No cartoon robot mascot heads',
      'No garish multi-colored neon clutter',
    ],
  },

  ORGANIC_LIFESTYLE: {
    id: 'ORGANIC_LIFESTYLE',
    name: 'Organic Lifestyle',
    description: 'Natural sun-dappled daylight, authentic biological textures, earthy palette, and heartwarming human warmth.',
    composition: {
      grid: 'Natural golden spiral composition drawing eye effortlessly through scene',
      focalPoint: 'Product naturally settled in an authentic, un-staged everyday life context',
      productScale: 'Harmonious 35-40% scale integrated naturally into the environment',
      productPosition: 'Resting on natural reclaimed wood table, sunny windowsill, or hand-held in use',
      humanPosition: 'Warm authentic human interaction: genuine smile, hands harvesting or preparing',
      negativeSpace: 'Warm airy atmospheric negative space where sunlight floods the room',
      cropStrategy: 'Environmental portrait crop showcasing genuine context and lifestyle setting',
      cameraAngle: 'Warm eye-level point-of-view perspective fostering emotional trust',
      depthLayers: ['Soft foreground foliage or morning coffee steam', 'In-focus hero product in use', 'Authentic human expression', 'Sun-drenched natural background'],
    },
    artDirection: {
      visualLanguage: 'Authentic living, farm-to-table freshness, wholesome sustainability',
      materialLanguage: 'Raw oak, terracotta, organic unbleached cotton, botanical leaves, ceramic',
      lighting: 'Golden morning window daylight with warm directional sunbeams and dappled leaf shadows',
      backgroundTreatment: 'Airy sunlit kitchen, lush green greenhouse, or rustic outdoor orchard',
      colorTreatment: 'Warm earthy tones: terracotta, sage green, raw honey, warm cream',
      contrastStrategy: 'Soft natural contrast with gentle shadow rolloff and warm highlights',
      texture: 'Natural wood grain, botanical leaf veins, water dew drops, fabric weave',
      atmosphere: 'Wholesome, comforting, refreshing, deeply trustworthy',
    },
    graphicLanguage: {
      shapes: ['Soft organic rounded badges', 'Handcrafted seal stamps'],
      frames: ['Gentle thin hairline border with rounded corners'],
      lines: ['Soft dotted botanical separator rules'],
      panels: ['Warm ivory translucent badges with soft drop shadows'],
      glow: 'Golden optical lens flare from natural morning sunlight',
      grain: 'Warm analog medium format film grain (Kodak Portra feel)',
      decorativeMotifs: ['100% Doğal / Organik verification stamps', 'Botanical sprig icons'],
    },
    typographyDirection: {
      headlineCharacter: 'Warm humanistic serif or friendly clean rounded sans-serif',
      hierarchy: 'Inviting conversational headline with authentic benefit promise',
      alignment: 'Left aligned or centered with generous organic breathing room',
      density: 'Airy, relaxed, inviting, anti-commercial pressure',
      styleFeel: 'Kinfolk magazine, artisanal food brand, premium wellness editorial',
    },
    bestForObjectives: ['PRODUCT_INTRO', 'BRAND_AWARENESS', 'REAL_USAGE'],
    antiGenericRules: [
      'No artificial plastic fruit or fake studio green screens',
      'No cold corporate blue hues or harsh digital grids',
      'No aggressive flashing SALE starbursts',
    ],
  },

  INDUSTRIAL_POWER: {
    id: 'INDUSTRIAL_POWER',
    name: 'Industrial Power',
    description: 'Heavy architectural steel, raw concrete, spark showers, structural grids, and unshakeable engineering durability.',
    composition: {
      grid: 'Rigid structural construction grid based on industrial steel beams',
      focalPoint: 'Heavy-duty equipment or industrial product commanding the lower two-thirds',
      productScale: 'Massive 60-70% presence conveying overwhelming durability and scale',
      productPosition: 'Firmly anchored on industrial diamond-plate steel or rough cured concrete',
      humanPosition: 'Equipped construction engineer or specialist in PPE operating or inspecting',
      negativeSpace: 'Upper structural sky/ceiling quadrant reserved for bold technical headline',
      cropStrategy: 'Heroic wide-angle close-up emphasizing structural fasteners, welds, and finish',
      cameraAngle: 'Low perspective looking up (20 degrees) emphasizing monumental strength',
      depthLayers: ['Crisp industrial surface with sparks or dust', 'Heavy-duty product in tack-sharp focus', 'Active factory floor / construction site depth', 'Moody industrial sky or high-bay factory lights'],
    },
    artDirection: {
      visualLanguage: 'Uncompromising durability, engineering excellence, heavy-duty reliability',
      materialLanguage: 'Toughened steel, textured powder-coat, reinforced concrete, diamond plate',
      lighting: 'High-contrast directional industrial work lighting with intense rim highlights',
      backgroundTreatment: 'Active construction jobsite, modern precast factory, or steel fabrication shop',
      colorTreatment: 'Safety yellow/orange and industrial brand accents on deep charcoal & steel grey',
      contrastStrategy: 'Aggressive industrial contrast with specular highlights on machined metal',
      texture: 'Rough concrete aggregate, welding beads, machined knurling, metal grain',
      atmosphere: 'Indomitable, heavy-duty, certified, unstoppable productivity',
    },
    graphicLanguage: {
      shapes: ['Hexagonal technical badges', 'Hazard-stripe indicator bars', 'Structural brackets'],
      frames: ['Heavy industrial corner brackets and technical framing marks'],
      lines: ['Precision dimension leader lines with measurement markers'],
      panels: ['Matte black technical specification data panels'],
      glow: 'Hot welding spark or industrial LED status indicator point-source glow',
      grain: 'Crisp industrial photography sharpness with raw grit',
      decorativeMotifs: ['ISO/CE certification badges', 'Load capacity / durability metric tags'],
    },
    typographyDirection: {
      headlineCharacter: 'Monumental condensed industrial sans-serif (DIN / Impact / Eurostile style)',
      hierarchy: 'Commanding industrial headline backed by certified specification callouts',
      alignment: 'Flushed left with heavy structural block weighting',
      density: 'Direct, informative, authoritative, zero fluff',
      styleFeel: 'Caterpillar / Bosch Professional / Hilti engineering campaign',
    },
    bestForObjectives: ['PRODUCT_HERO', 'NEW_PRODUCT', 'CAMPAIGN'],
    antiGenericRules: [
      'No flimsy delicate pastel lines',
      'No stock photos of models pretending to hold tools backwards',
      'No cartoon hard-hat illustrations',
    ],
  },

  ARCHITECTURAL_PRESTIGE: {
    id: 'ARCHITECTURAL_PRESTIGE',
    name: 'Architectural Prestige',
    description: 'Monumental facade geometry, dramatic perspective vanishing points, raw luxury materials, and civic pride.',
    composition: {
      grid: 'Two-point architectural perspective grid with sweeping vertical lines',
      focalPoint: 'Architectural monument, real estate facade, or construction material hero',
      productScale: 'Integrated masterfully across 50% of the visual perspective field',
      productPosition: 'Seamlessly installed into a premier architectural facade or interior structure',
      humanPosition: 'Silhouetted architectural figures illustrating scale and human proportion',
      negativeSpace: 'Expansive open sky or clean concrete ceiling reserved for prestige headline',
      cropStrategy: 'Wide-angle tilt-shift architectural crop maintaining strictly vertical lines',
      cameraAngle: 'Elevated architectural viewpoint showcasing scale, structural grid, and context',
      depthLayers: ['Foreground landscaped reflection pool or plaza', 'Hero facade/building in razor clarity', 'Sunlight glancing off glass & stone', 'Clean open horizon'],
    },
    artDirection: {
      visualLanguage: 'Civic prestige, timeless investment, generational durability',
      materialLanguage: 'Clinker brick, exposed concrete, bronze cladding, structural glazing',
      lighting: 'Crisp late-afternoon raking sun revealing facade textures and deep reveal shadows',
      backgroundTreatment: 'Pristine blue architectural sky or contemporary urban setting',
      colorTreatment: 'Rich natural masonry tones: terracotta, charcoal basalt, warm bronze accents',
      contrastStrategy: 'Architectural solar contrast between direct sunlit face and shadow reveals',
      texture: 'Fired brick texture, honed stone seams, glass reflections, architectural mortar',
      atmosphere: 'Monumental, prestigious, permanent, visionary development',
    },
    graphicLanguage: {
      shapes: ['Architectural elevation blueprints', 'Minimalist square floorplan markers'],
      frames: ['Clean rectangular architectural boundary frames with coordinate markers'],
      lines: ['Fine perspective guidelines and horizon level indicators'],
      panels: ['Frosted glass architectural specification capsules'],
      glow: 'Golden hour solar flare reflecting off glass corners',
      grain: 'Ultra-high resolution large format architectural camera clarity',
      decorativeMotifs: ['Location coordinate tags', 'Architectural award seal stamps'],
    },
    typographyDirection: {
      headlineCharacter: 'Refined architectural grotesque or geometric sans-serif with wide spacing',
      hierarchy: 'Prestigious project title dominant, supported by location & delivery date specs',
      alignment: 'Left aligned along the principal architectural column grid',
      density: 'Restrained, authoritative, projecting elite investment security',
      styleFeel: 'Zaha Hadid Architects publication, Architectural Digest feature cover',
    },
    bestForObjectives: ['BRAND_AWARENESS', 'NEW_PRODUCT'],
    antiGenericRules: [
      'No warped AI building facades with melting windows',
      'No tacky cartoon keys or fake discount balloon graphics',
      'No generic 3D clip-art houses',
    ],
  },

  FOOD_APPETITE: {
    id: 'FOOD_APPETITE',
    name: 'Food Appetite',
    description: 'Irresistible macro-texture, glistening glaze, fresh steam, vibrant ingredient explosion, and mouthwatering urgency.',
    composition: {
      grid: 'Dynamic circular dining composition with radial energy flow',
      focalPoint: 'Tantalizing hero bite, glistening fresh glaze, or aromatic steam plume',
      productScale: 'Close-up hero scale commanding 60-70% of the canvas frame',
      productPosition: 'Artfully plated on handcrafted ceramic dish or rustic wooden board',
      humanPosition: 'Chef’s hand adding final garnish or joyful diner about to take first bite',
      negativeSpace: 'Upper or side quadrant with warm ambient backdrop for offer and CTA',
      cropStrategy: 'Sensual macro close-up highlighting food texture, freshness, and crust',
      cameraAngle: '45-degree classic dining perspective or dynamic top-down flatlay',
      depthLayers: ['Foreground falling spices/parsley garnish', 'Ultra-sharp glistening food hero', 'Rising translucent steam plume', 'Soft out-of-focus dining ambience'],
    },
    artDirection: {
      visualLanguage: 'Hyper-fresh, freshly prepared, artisanal culinary craftsmanship',
      materialLanguage: 'Glazed porcelain, charred oak, cast iron, parchment, fresh herb leaves',
      lighting: 'Warm 3200K side-backlight creating glistening specular highlights and illuminating steam',
      backgroundTreatment: 'Warm buzzing restaurant kitchen or rustic dining table with wine glass bokeh',
      colorTreatment: 'Warm appetitive reds, golden yellows, rich roasted browns, fresh herb greens',
      contrastStrategy: 'Rich warm contrast with mouthwatering specular highlights on sauces and oils',
      texture: 'Crispy golden crust, melting cheese stretch, juicy meat grain, dew on greens',
      atmosphere: 'Intensely appetizing, fresh from the oven, crave-worthy indulgence',
    },
    graphicLanguage: {
      shapes: ['Appetizing circular flavor badges', 'Freshness guarantee seals'],
      frames: ['Warm organic hairline borders with soft inner vignette'],
      lines: ['Delicate menu separator rules with chef knife or fork motif'],
      panels: ['Warm cream or deep burgundy offer tags with delivery badge'],
      glow: 'Warm golden specular glisten on culinary highlights',
      grain: 'Crisp food photography clarity with warm organic depth',
      decorativeMotifs: ['"Günlük Taze" / "Özel Soslu" chef recommendation badges'],
    },
    typographyDirection: {
      headlineCharacter: 'Bold expressive display typography with artisanal culinary warmth',
      hierarchy: 'Mouthwatering menu item name dominant, accompanied by ingredients & price',
      alignment: 'Centered or left-aligned with appetizing layout balance',
      density: 'Scannable, focused on triggering immediate taste cravings',
      styleFeel: 'Michelin star gastro-pub menu, premium food magazine cover',
    },
    bestForObjectives: ['SALES_OFFER', 'CAMPAIGN', 'DYNAMIC_OFFER'],
    antiGenericRules: [
      'No plastic-looking fake fast-food 3D models',
      'No cold unappetizing bluish lighting on cooked food',
      'No unreadable tiny ingredient lists',
    ],
  },

  CLINICAL_PREMIUM: {
    id: 'CLINICAL_PREMIUM',
    name: 'Clinical Premium',
    description: 'Pristine sterile white, calibrated medical precision, serene trustworthiness, and gentle scientific authority.',
    composition: {
      grid: 'Balanced symmetrical laboratory grid with calming horizontal vectors',
      focalPoint: 'Hero healthcare product or dental/dermal innovation in pure light',
      productScale: 'Disciplined 40-45% scale surrounded by pristine calming space',
      productPosition: 'Resting on flawless white composite or floating above a clean glass plinth',
      humanPosition: 'Professional clinician or smiling patient radiating calm health and confidence',
      negativeSpace: '50% immaculate white/soft-cyan negative space projecting cleanliness',
      cropStrategy: 'Clean frontal showcase with ample breathing room on all sides',
      cameraAngle: 'Direct straight-on eye-level angle inspiring complete trust',
      depthLayers: ['Crisp foreground product', 'Soft reflection on white surface', 'Gentle clinical depth gradient', 'Pristine bright ambient light'],
    },
    artDirection: {
      visualLanguage: 'Scientific verification, dermatological purity, painless precision',
      materialLanguage: 'Pristine composite, frosted medical glass, titanium, brushed white ceramic',
      lighting: 'Ultra-soft shadowless clinical illumination with subtle blue-white rim separation',
      backgroundTreatment: 'Flawless bright laboratory cove or minimalist modern aesthetic clinic',
      colorTreatment: 'Pure medical whites, calming cyan/aquamarine accents, soft silver gray',
      contrastStrategy: 'High-key lighting with gentle soft shadows and surgical clarity',
      texture: 'Flawlessly smooth medical surfaces, microscopic water hydration droplets',
      atmosphere: 'Calm, certified, hygienic, pain-free, reassuringly expert',
    },
    graphicLanguage: {
      shapes: ['Medical cross capsules', 'Clinical test score badges', 'Shield icons'],
      frames: ['Minimal rounded clinical borders with 1px hairline stroke'],
      lines: ['Calibrated horizontal measurement scales'],
      panels: ['Pure white floating cards with soft 4% drop shadow'],
      glow: 'Subtle clean optical purity glow on active product elements',
      grain: 'Absolute zero noise, sterile clinical purity',
      decorativeMotifs: ['Dermatologically Tested / Uzman Onaylı verification badges'],
    },
    typographyDirection: {
      headlineCharacter: 'Clean neutral grotesque sans-serif with impeccable legibility and calm spacing',
      hierarchy: 'Clear health benefit headline followed by certified clinical proof points',
      alignment: 'Left aligned or centered with generous clinical spacing',
      density: 'Low density, zero visual anxiety or aggressive commercial pressure',
      styleFeel: 'Swiss dermatological skincare campaign, elite dental clinic branding',
    },
    bestForObjectives: ['PRODUCT_INTRO', 'BRAND_AWARENESS'],
    antiGenericRules: [
      'No scary surgical instruments or blood/gore imagery',
      'No chaotic cluttered elements causing patient anxiety',
      'No cheesy cartoon tooth mascots',
    ],
  },

  FUTURISTIC_DATA: {
    id: 'FUTURISTIC_DATA',
    name: 'Futuristic Data',
    description: 'Cybernetic depth, volumetric light tunnels, holographic data nodes, and AI-era technological supremacy.',
    composition: {
      grid: 'Deep 3D perspective grid with vanishing point pulling eyes through data tunnel',
      focalPoint: 'Central AI core, software product, or data dashboard emitting volumetric light',
      productScale: 'Heroic 50% scale radiating holographic data rings and network connections',
      productPosition: 'Hovering effortlessly in a magnetic zero-gravity data chamber',
      humanPosition: 'Futuristic analyst with augmented digital HUD overlay',
      negativeSpace: 'Structured telemetry quadrant for headline and KPI callouts',
      cropStrategy: 'Wide dynamic perspective with deep visual falloff',
      cameraAngle: 'Slightly low isometric angle capturing multi-tier holographic layers',
      depthLayers: ['Foreground floating data nodes', 'Central luminous product core', 'Concentric holographic telemetry rings', 'Infinite dark cybernetic grid horizon'],
    },
    artDirection: {
      visualLanguage: 'Autonomous AI, quantum processing, cybernetic velocity, data supremacy',
      materialLanguage: 'Dark obsidian glass, liquid chrome, holographic prisms, fiber-optic filaments',
      lighting: 'Internal bioluminescent and laser-etched edge lighting in deep dark-field environment',
      backgroundTreatment: 'Infinite perspective cyber grid with volumetric light beams and data streams',
      colorTreatment: 'Electric cyan, deep indigo, neon violet accents on deep void black',
      contrastStrategy: 'Extreme high dynamic range: brilliant light emitters on pure black void',
      texture: 'Optical diffractions, holographic film sheen, micro-circuit traces',
      atmosphere: 'Visionary, revolutionary, all-powerful, next-era technological leap',
    },
    graphicLanguage: {
      shapes: ['Hexagonal data pods', 'Concentric telemetry rings', 'Holographic badges'],
      frames: ['Cybernetic HUD corner brackets with coordinate marks'],
      lines: ['Glowing vector data streams and circuit connector traces'],
      panels: ['Semi-transparent holographic HUD data panels with scanlines'],
      glow: 'Volumetric laser bloom and optical chromatic aberration on glowing edges',
      grain: 'Subtle high-tech digital grain overlay',
      decorativeMotifs: ['Real-time throughput metrics (99.9% Uptime, 0.1ms Latency)'],
    },
    typographyDirection: {
      headlineCharacter: 'Technical monospace or futuristic wide-tracked geometric sans-serif',
      hierarchy: 'Data-driven headline paired with real-time KPI metrics and action button',
      alignment: 'Left aligned within cybernetic HUD frame',
      density: 'High-tech scannable telemetry aesthetic',
      styleFeel: 'Cyberpunk 2077 UI, Palantir enterprise dashboard, DeepMind research reveal',
    },
    bestForObjectives: ['NEW_PRODUCT', 'PRODUCT_HERO'],
    antiGenericRules: [
      'No cheesy 1990s green-matrix cascading numbers',
      'No fake cartoon lightning bolts',
      'No illegible tiny sci-fi gibberish',
    ],
  },

  MAGAZINE_COVER: {
    id: 'MAGAZINE_COVER',
    name: 'Magazine Cover',
    description: 'Iconic masthead hierarchy, curated editorial cover lines, celebrity hero staging, and prestige cultural authority.',
    composition: {
      grid: 'Classic editorial publication grid with top masthead zone and flanking cover lines',
      focalPoint: 'Hero subject interacting decisively with the imaginary top masthead',
      productScale: 'Hero occupies 70% of canvas, overlapping or tucked under masthead branding',
      productPosition: 'Posed with iconic editorial charisma against a studio backdrop',
      humanPosition: 'Charismatic brand ambassador or model making direct magnetic eye contact',
      negativeSpace: 'Structured vertical side columns reserved for editorial cover lines',
      cropStrategy: 'Classic vertical editorial portrait crop (bust or full body)',
      cameraAngle: 'Classic editorial eye-level medium shot (85mm lens feel)',
      depthLayers: ['Top masthead branding layer', 'Hero subject overlapping text', 'Side cover line typography', 'Curated solid studio backdrop'],
    },
    artDirection: {
      visualLanguage: 'Prestige journalism, trendsetting authority, high-fashion cover story',
      materialLanguage: 'Glossy magazine stock, tailored couture fabrics, polished studio cyclorama',
      lighting: 'Flawless Hasselblad studio lighting: giant parabolic umbrella key + subtle rim hair light',
      backgroundTreatment: 'Rich solid seamless studio paper (deep emerald, crimson, or warm studio beige)',
      colorTreatment: 'Sophisticated color harmony: single saturated backdrop tone + monochrome wardrobe',
      contrastStrategy: 'Flattering medium contrast with velvety shadows and luminous skin tones',
      texture: 'Crisp fabric weave, healthy skin texture, glossy paper sheen',
      atmosphere: 'Iconic, culturally influential, exclusive, trendsetting',
    },
    graphicLanguage: {
      shapes: ['Editorial issue badges', 'Barcode corner stamp', 'Special edition seals'],
      frames: ['Classic publication bleed border with inner 15px hairline margin'],
      lines: ['Fine horizontal rule dividing issue date from brand masthead'],
      panels: ['Minimal editorial feature boxes for secondary stories'],
      glow: 'Zero glow, pure photographic print aesthetic',
      grain: 'Fine medium-format 120mm photographic film grain',
      decorativeMotifs: ['"ÖZEL SAYI" / "YILIN ÜRÜNÜ" prestige badge stamps', 'Issue number indicator'],
    },
    typographyDirection: {
      headlineCharacter: 'Bold iconic masthead typography paired with sharp editorial serif cover lines',
      hierarchy: 'Hero masthead top, dominant cover story headline, 2-3 concise teaser lines',
      alignment: 'Left and right justified editorial column blocks',
      density: 'Rich editorial information hierarchy balanced with visual breathing room',
      styleFeel: 'Time Magazine / GQ / Vogue / Monocle official cover edition',
    },
    bestForObjectives: ['BRAND_AWARENESS', 'CAMPAIGN'],
    antiGenericRules: [
      'No amateur crooked text angles',
      'No ugly supermarket discount bubbles over the hero face',
      'No blurry low-res background stock photos',
    ],
  },

  COLLAGE_CAMPAIGN: {
    id: 'COLLAGE_CAMPAIGN',
    name: 'Collage Campaign',
    description: 'Postmodern mixed-media layering, torn paper textures, tape accents, polaroid insets, and high-fashion streetwear energy.',
    composition: {
      grid: 'Asymmetrical layered z-index collage grid with overlapping physical elements',
      focalPoint: 'Hero product anchored in central cutout framed by layered tactile fragments',
      productScale: 'Hero product at 50% scale breaking free from an underlying frame',
      productPosition: 'Dynamic cutout layering with realistic cast shadow over background panels',
      humanPosition: 'Expressive streetwear talent captured in candid snapshot aesthetic',
      negativeSpace: 'Dynamic negative space created by intentional paper tear angles',
      cropStrategy: 'Eclectic mixed crop combining macro product close-up with wide lifestyle polaroid',
      cameraAngle: 'Mixed perspective: direct product shot over candid 35mm film snap',
      depthLayers: ['Foreground washi tape and stamp accents', 'Hero cutout subject with drop shadow', 'Layered polaroid and paper scrap panels', 'Textured craft paper background'],
    },
    artDirection: {
      visualLanguage: 'Raw authenticity, creative streetwear zine, Gen-Z cultural momentum',
      materialLanguage: 'Torn heavy cardstock, transparent washi tape, kraft paper, polaroid frames',
      lighting: 'Direct on-camera flash combined with natural ambient lifestyle light',
      backgroundTreatment: 'Textured concrete wall, craft cardboard, or wheat-pasted poster wall',
      colorTreatment: 'Vibrant CMYK print colors combined with raw natural paper tones',
      contrastStrategy: 'Raw flash contrast with punchy blacks and pure paper highlights',
      texture: 'Torn fibrous paper edges, adhesive tape wrinkles, risograph print dot matrix',
      atmosphere: 'Creative, unfiltered, authentic, artistically rebellious, viral',
    },
    graphicLanguage: {
      shapes: ['Torn paper fragments', 'Adhesive tape strips', 'Rubber stamp circles'],
      frames: ['Classic vintage Polaroid border frames with handwritten captions'],
      lines: ['Hand-drawn marker underlines and directional arrows'],
      panels: ['Angled paper cutout cards pinned to canvas'],
      glow: 'Zero glow, pure tactile analog physical collage feel',
      grain: 'Authentic xerox photocopy grain and 35mm flash film grain',
      decorativeMotifs: ['Barcode stickers', 'Rubber-stamped approval seals', 'Price tag stickers'],
    },
    typographyDirection: {
      headlineCharacter: 'Bold utilitarian grotesque mixed with authentic handwritten script accents',
      hierarchy: 'Striking paste-up headline with handwritten price/promo notes',
      alignment: 'Slightly angled or dynamic staggered alignment breaking rigid grids',
      density: 'Visually rich, packed with discoverable tactile details',
      styleFeel: 'Stüssy / Supreme lookbook, Nike SB skate zine, Off-White exhibition poster',
    },
    bestForObjectives: ['CAMPAIGN', 'DYNAMIC_OFFER', 'NEW_PRODUCT'],
    antiGenericRules: [
      'No clean sterile corporate templates',
      'No generic fake 3D glossy icons',
      'No boring symmetrical corporate layouts',
    ],
  },

  MATERIAL_TEXTURE_HERO: {
    id: 'MATERIAL_TEXTURE_HERO',
    name: 'Material Texture Hero',
    description: 'Hyper-detailed tactile close-up celebrating raw physical substance: liquid splashes, stone grain, metal knurling.',
    composition: {
      grid: 'Macro split grid dividing raw raw substance from finished product',
      focalPoint: 'The tactile collision point where product meets its raw natural material',
      productScale: 'Substantial 55% scale surrounded by swirling raw physical textures',
      productPosition: 'Emerging majestically from its core raw ingredient or material base',
      humanPosition: 'Artisan or master craftsman hands shaping or inspecting the material',
      negativeSpace: 'Calm negative space quadrant opposing the dynamic material explosion',
      cropStrategy: 'Extreme tactile medium shot emphasizing physical material density',
      cameraAngle: 'Low raking angle capturing surface relief and textural ridges',
      depthLayers: ['Macro foreground splash/texture fragments', 'Ultra-sharp hero product', 'Swirling ingredient/material wave', 'Graduated atmospheric backdrop'],
    },
    artDirection: {
      visualLanguage: 'Authentic physical craftsmanship, raw material honesty, visceral sensory impact',
      materialLanguage: 'Crushed spices, virgin olive oil splash, raw clay, pulverized stone, molten bronze',
      lighting: 'Harsh directional raking light sculpting every ridge, bubble, and grain with micro-shadows',
      backgroundTreatment: 'Natural slate slab, weathered wood workbench, or smooth granite surface',
      colorTreatment: 'Hyper-rich organic material palette derived directly from the physical product',
      contrastStrategy: 'Extreme textural micro-contrast highlighting microscopic surface details',
      texture: 'Viscous liquid droplets, rough mineral fracture lines, polished metal highlights',
      atmosphere: 'Sensory, physical, authentic, masterfully crafted, unadulterated quality',
    },
    graphicLanguage: {
      shapes: ['Minimal circular material origin badges', 'Purity guarantee seals'],
      frames: ['Ultra-fine hairline frame inset from canvas edge'],
      lines: ['Technical ingredient connection lines pointing to core materials'],
      panels: ['Matte translucent description panels with subtle shadow'],
      glow: 'Crisp specular glisten on liquid surfaces and polished edges',
      grain: 'Ultra-crisp macro photography sharpness with natural physical grain',
      decorativeMotifs: ['%100 Saf / Doğal Üretim certified craft seals'],
    },
    typographyDirection: {
      headlineCharacter: 'Craft-inspired modern serif or understated technical grotesque',
      hierarchy: 'Direct material declaration headline backed by craft origin details',
      alignment: 'Flush left with generous negative space separation from material textures',
      density: 'Moderate density, letting the visceral material texture do the selling',
      styleFeel: 'Aesop campaign, single-malt whiskey packaging monograph, artisanal studio',
    },
    bestForObjectives: ['PRODUCT_HERO', 'PRODUCT_INTRO', 'BRAND_AWARENESS'],
    antiGenericRules: [
      'No flat plastic CGI renders without micro-texture',
      'No generic pastel gradient backgrounds',
      'No fake stock-photo cartoon sparkles',
    ],
  },

  STUDIO_PEDESTAL: {
    id: 'STUDIO_PEDESTAL',
    name: 'Studio Pedestal',
    description: 'Sculptural architectural podium, flawless museum lighting, pristine geometric staging, and undeniable prestige.',
    composition: {
      grid: 'Classic museum pedestal vertical symmetry with balanced negative space',
      focalPoint: 'Hero product elevated proudly upon a sculpted geometric pedestal',
      productScale: 'Hero occupies 45% of height, reigning supreme atop its plinth',
      productPosition: 'Resting on a tiered circular or rectangular honed marble/concrete pedestal',
      humanPosition: 'None — pure museum gallery worship of the hero object',
      negativeSpace: '40% pristine studio negative space framing the sculptural pedestal',
      cropStrategy: 'Full pedestal-to-product vertical showcase with grounded foundation',
      cameraAngle: 'Slightly low museum viewing angle (10 degrees upward) inspiring reverence',
      depthLayers: ['Pedestal base contact shadow', 'Razor-sharp product on plinth', 'Soft directional wall shadow', 'Infinite seamless studio background'],
    },
    artDirection: {
      visualLanguage: 'Museum exhibit, architectural gallery, sacred design object',
      materialLanguage: 'Carrara marble, cast terrazzo, honed concrete, smoked glass plinth',
      lighting: 'Gallery ceiling spotlight with soft directional fill and razor-sharp ground shadow',
      backgroundTreatment: 'Curved seamless studio cyclorama in warm limestone or cool slate gray',
      colorTreatment: 'Sophisticated monochromatic architectural tones with brand accent on product',
      contrastStrategy: 'Sculptural volumetric contrast accentuating geometric form and planes',
      texture: 'Micro-polished stone veining, matte cast composite, smooth ambient shadows',
      atmosphere: 'Exquisite, revered, permanent, masterwork design standard',
    },
    graphicLanguage: {
      shapes: ['Minimalist architectural exhibition plaques', 'Pedestal outline guides'],
      frames: ['Fine gallery boundary frame with exhibition index numbers'],
      lines: ['Vertical architectural plumb lines anchoring the pedestal axis'],
      panels: ['Frosted acrylic gallery info cards with clean typography'],
      glow: 'Soft overhead spotlight cone bloom',
      grain: 'Fine velvety studio camera grain',
      decorativeMotifs: ['Exhibit identification index (01/24)', 'Gallery curator verification seal'],
    },
    typographyDirection: {
      headlineCharacter: 'Understated contemporary grotesque with generous tracking (Neue Haas / Swiss 721 style)',
      hierarchy: 'Monumental single-phrase headline with understated product specifications',
      alignment: 'Centered above pedestal or left-aligned in upper negative space',
      density: 'Minimal density, maximum prestige breathing room',
      styleFeel: 'MoMA exhibition catalog, Bang & Olufsen flagship catalog, Vitra design poster',
    },
    bestForObjectives: ['BRAND_AWARENESS', 'NEW_PRODUCT', 'PREMIUM'],
    antiGenericRules: [
      'No tacky disco lighting or multi-color party gradients',
      'No floating or crooked pedestals that violate gravity',
      'No cheesy discount starbursts glued to the artwork',
    ],
  },

  REAL_WORLD_USAGE: {
    id: 'REAL_WORLD_USAGE',
    name: 'Real World Usage',
    description: 'Documentary realism, decisive real-world action, natural wear, working environment depth, and honest proof.',
    composition: {
      grid: 'Rule of thirds documentary grid capturing unscripted working moment',
      focalPoint: 'Product performing its primary function in active real-world conditions',
      productScale: 'Natural working scale (35-45%) in active hands or on active job surface',
      productPosition: 'In active deployment: spraying crops, assembling masonry, running software',
      humanPosition: 'Authentic skilled operator, technician, or customer in natural work attire',
      negativeSpace: 'Open environmental sector sky or workshop space for headline placement',
      cropStrategy: 'Action medium close-up capturing both the product action and operator focus',
      cameraAngle: 'Immersive photojournalistic eye-level angle placing viewer in the action',
      depthLayers: ['Foreground work debris/spray mist', 'Active product in crisp working focus', 'Focused operator hands/face', 'Authentic jobsite/field background'],
    },
    artDirection: {
      visualLanguage: 'Hardworking authenticity, battle-tested durability, proven reliability',
      materialLanguage: 'Working soil, construction mortar, tool steel, authentic workwear canvas',
      lighting: 'Natural ambient working light: overcast diffused daylight or functional workshop lamps',
      backgroundTreatment: 'Genuine Turkish agricultural field, active building project, or actual modern office',
      colorTreatment: 'Authentic documentary color grading with natural environmental saturation',
      contrastStrategy: 'True-to-life documentary contrast, natural highlights without artificial burn',
      texture: 'Authentic dust, water mist, soil grains, worn tool grips, working fabric weave',
      atmosphere: 'Honest, hardworking, reliable, proven on the job, completely un-staged',
    },
    graphicLanguage: {
      shapes: ['Rugged field-tested certification badges', 'Documentary date stamps'],
      frames: ['Clean rectangular border with subtle photojournalist field marks'],
      lines: ['Functional divider lines separating field proof from offer copy'],
      panels: ['High-contrast white or yellow offer capsules ensuring instant mobile read'],
      glow: 'Zero artificial glow, authentic sunlight or workshop lamp highlights',
      grain: 'Crisp photojournalism camera grain with high dynamic range',
      decorativeMotifs: ['"Sahada Test Edildi" / "Gerçek Kullanıcı Onaylı" trust badges'],
    },
    typographyDirection: {
      headlineCharacter: 'Direct, honest, heavy-duty grotesque sans-serif with zero pretension',
      hierarchy: 'Compelling benefit headline backed by real-world performance proof',
      alignment: 'Left aligned with strong horizontal baseline grounding',
      density: 'Direct, punchy, easy to absorb in fast mobile scrolling',
      styleFeel: 'National Geographic documentary feature, DeWalt field report, authentic testimonial',
    },
    bestForObjectives: ['REAL_USAGE', 'PRODUCT_INTRO', 'SALES_OFFER'],
    antiGenericRules: [
      'No smiling stock models holding clean tools with no work done',
      'No sterile laboratory settings pretending to be real jobsites',
      'No fantasy sci-fi effects in a practical working scenario',
    ],
  },

  MAXIMALIST_PROMO: {
    id: 'MAXIMALIST_PROMO',
    name: 'Maximalist Promo',
    description: 'High-density commercial urgency, bold typography blocks, stacked benefit pills, and explosive conversion power.',
    composition: {
      grid: 'Dense modular newspaper layout packed with high-converting promotional zones',
      focalPoint: 'Hero product breaking through bold typography and promotional price badges',
      productScale: 'Prominent 50% scale layered dynamically between headline and price badge',
      productPosition: 'Angled forward aggressively with drop shadow over promotional panels',
      humanPosition: 'Excited brand ambassador gesturing directly toward the limited-time offer',
      negativeSpace: 'Zero wasted space: every quadrant is optimized for conversion and clarity',
      cropStrategy: 'Tight, packed commercial crop maximizing on-screen retail presence',
      cameraAngle: 'Direct forward-facing commercial angle with maximum optical impact',
      depthLayers: ['Floating discount pill badge', 'Hero product in razor sharpness', 'Bold typography background layer', 'High-contrast split-tone backdrop'],
    },
    artDirection: {
      visualLanguage: 'High-conversion commercial urgency, limited-time blockbuster, can’t-miss deal',
      materialLanguage: 'High-gloss print paper, bold vinyl banner materials, saturated commercial acrylic',
      lighting: 'Bright, shadowless commercial studio lighting with punchy rim separation',
      backgroundTreatment: 'Vibrant geometric color block split (e.g. brand primary + dynamic accent)',
      colorTreatment: 'High-contrast commercial palette with bright urgent badge colors (coral/yellow/emerald)',
      contrastStrategy: 'Punchy commercial contrast designed to stop mobile feed scrollers instantly',
      texture: 'Clean crisp commercial surfaces, razor-sharp text edges',
      atmosphere: 'Urgent, exciting, irresistible, massive savings, limited opportunity',
    },
    graphicLanguage: {
      shapes: ['Bold rounded percentage pills', 'High-visibility price capsules', 'Urgency countdown tags'],
      frames: ['Thick high-contrast outer frame with inner neon accent line'],
      lines: ['Bold horizontal strike-through rules on old price and section dividers'],
      panels: ['Solid high-contrast background panels for delivery and warranty badges'],
      glow: 'Subtle perimeter luminescence around key offer badges',
      grain: 'Crisp digital zero-noise commercial sharpness',
      decorativeMotifs: ['"SINIRLI SAYIDA" / "AYIN FIRSATI" / "KAMPANYA" headline banners'],
    },
    typographyDirection: {
      headlineCharacter: 'Massive ultra-heavy grotesque sans-serif with maximum ink coverage',
      hierarchy: 'Huge offer percentage/price dominant, followed by punchy headline and bold CTA',
      alignment: 'Centered or strong block alignment with zero awkward line breaks',
      density: 'High density, structured modular layout, immediately readable on 5-inch screens',
      styleFeel: 'Trendyol Mega Eylül / Black Friday blockbuster retail campaign',
    },
    bestForObjectives: ['SALES_OFFER', 'CAMPAIGN', 'DYNAMIC_OFFER'],
    antiGenericRules: [
      'No tacky 90s yellow starburst stickers with jagged comic edges',
      'No unreadable tiny text or blurry pixelated badges',
      'No confusing layout where the customer cannot find the price or product',
    ],
  },

  CLEAN_CORPORATE: {
    id: 'CLEAN_CORPORATE',
    name: 'Clean Corporate',
    description: 'Corporate governance, institutional trust, crisp blue-chip typography, and executive-level authority.',
    composition: {
      grid: 'Impeccable 12-column corporate annual report grid with mathematical precision',
      focalPoint: 'Corporate product, B2B software dashboard, or executive brand showcase',
      productScale: 'Disciplined 40% scale balanced with spacious corporate messaging zones',
      productPosition: 'Elegantly positioned on executive walnut conference desk or modern glass podium',
      humanPosition: 'Confident, well-tailored business leader or engineering director in natural executive pose',
      negativeSpace: 'Spacious 45% executive negative space conveying stability and scale',
      cropStrategy: 'Balanced medium corporate environmental portrait or clean product isolation',
      cameraAngle: 'Straight-on eye-level executive perspective inspiring confidence and security',
      depthLayers: ['Crisp foreground product/document', 'Executive talent in natural focus', 'Soft modern architectural office background', 'Sunlit skyline through boardroom glass'],
    },
    artDirection: {
      visualLanguage: 'Institutional stability, blue-chip reliability, enterprise security, certified excellence',
      materialLanguage: 'Executive walnut, brushed nickel, architectural glass, tailored Italian wool',
      lighting: 'Sophisticated architectural office daylight with soft flattering key light',
      backgroundTreatment: 'Modern glass-partitioned corporate headquarters with skyline bokeh',
      colorTreatment: 'Executive navy blue, slate gray, crisp white, with refined corporate gold/emerald accents',
      contrastStrategy: 'Balanced corporate contrast, clear clean midtones, zero harsh shadows',
      texture: 'Refined architectural glass, brushed metal hardware, executive paper stock',
      atmosphere: 'Authoritative, dependable, enterprise-grade, visionary leadership',
    },
    graphicLanguage: {
      shapes: ['Clean rectangular metric cards', 'Institutional shield icons', 'Verified partner badges'],
      frames: ['Subtle 1px corporate grey hairline border'],
      lines: ['Precision rule lines separating corporate credentials from campaign offer'],
      panels: ['Clean white or light-slate data panels with subtle 2px drop shadows'],
      glow: 'Zero glow, total corporate clarity and executive sobriety',
      grain: 'Pristine digital medium-format camera clarity',
      decorativeMotifs: ['ISO 9001 / KVKK / TSE Compliance verification badges', 'Partner logo trust strip'],
    },
    typographyDirection: {
      headlineCharacter: 'Authoritative neo-grotesque or corporate transitional serif (Inter / Helvetica / Georgia)',
      hierarchy: 'Clear executive value proposition headline backed by key institutional proof points',
      alignment: 'Left aligned along strict corporate grid margin',
      density: 'Moderate, professional, transparent, respectful of executive decision-makers',
      styleFeel: 'McKinsey quarterly report, Goldman Sachs insights, SAP enterprise launch',
    },
    bestForObjectives: ['BRAND_AWARENESS', 'PRODUCT_INTRO'],
    antiGenericRules: [
      'No juvenile comic fonts or informal slang',
      'No cheap stock photos of models shaking hands with empty smiles',
      'No chaotic unaligned elements or aggressive flashing banners',
    ],
  },

  SOCIAL_FIRST_BOLD: {
    id: 'SOCIAL_FIRST_BOLD',
    name: 'Social First Bold',
    description: 'Stop-the-scroll thumb-stopping composition, high-contrast vibrant pop, and instant Gen-Z & mobile clarity.',
    composition: {
      grid: 'Mobile viewport 9:16 / 4:5 vertical framing with center-weighted impact zone',
      focalPoint: 'Hero product staged with high-contrast color pop that immediately stops scrolling fingers',
      productScale: 'Commanding 55-60% scale centered directly in the thumb-zone sweet spot',
      productPosition: 'Dynamic slight tilt or floating levitation with bold cast shadow below',
      humanPosition: 'Creator or stylish young consumer reacting authentically to product',
      negativeSpace: 'Dedicated upper 25% zone for massive high-contrast 3-word headline',
      cropStrategy: 'Vertical tight crop designed specifically for Instagram Stories & TikTok feeds',
      cameraAngle: 'Direct smartphone POV angle creating intimate peer-to-peer connection',
      depthLayers: ['Bold headline overlay in safe zone', 'Hero product popping out of screen', 'Dynamic floating UI elements', 'Vibrant saturated dual-tone background'],
    },
    artDirection: {
      visualLanguage: 'Viral creator culture, thumb-stopping speed, hyper-engaging lifestyle appeal',
      materialLanguage: 'Glossy colorful acrylics, iridescent materials, smooth matte pastel backdrops',
      lighting: 'Ultra-bright high-CRI ring-light / softbox combo creating punchy catchlights',
      backgroundTreatment: 'Vibrant studio paper backdrop or modern aesthetic cafe / apartment corner',
      colorTreatment: 'Hyper-vibrant social palette: electric cobalt, sunset orange, matcha green, lilac',
      contrastStrategy: 'High saturation, high pop, optimized for bright mobile OLED screens',
      texture: 'Smooth clean surfaces with tactile pop, razor-sharp edge contrast',
      atmosphere: 'Fresh, addictive, trending, culturally relevant, irresistible to click',
    },
    graphicLanguage: {
      shapes: ['TikTok/Reels style interactive sticker badges', 'Emoji-style accent pills', 'Bold price chips'],
      frames: ['Subtle phone viewport indicator lines or dynamic outer neon glow border'],
      lines: ['Playful hand-drawn squiggle accents pointing to key features'],
      panels: ['Floating frosted glass cards with rounded 16px corners'],
      glow: 'Vibrant colored rim luminescence matching brand secondary color',
      grain: 'Clean crisp digital aesthetic with subtle organic punch',
      decorativeMotifs: ['"TREND" / "ÇOK SATAN" / "VİRAL" flame or star badges', 'Verified creator checkmark'],
    },
    typographyDirection: {
      headlineCharacter: 'Chunky, punchy modern display sans-serif (Cabinet Grotesk / Clash Display / Gilroy)',
      hierarchy: 'Super-concise 2-4 word hook headline, immediate price/promo callout, massive CTA',
      alignment: 'Centered or left-heavy punch block in the top third safe zone',
      density: 'Ultra-scannable in under 0.5 seconds of mobile feed scrolling',
      styleFeel: 'Duolingo viral social campaign, Spotify Wrapped aesthetic, Gymshark drop poster',
    },
    bestForObjectives: ['SALES_OFFER', 'CAMPAIGN', 'DYNAMIC_OFFER', 'PRODUCT_HERO'],
    antiGenericRules: [
      'No sleepy desaturated brown tones that disappear in mobile feeds',
      'No long paragraphs or tiny unreadable disclaimer fonts',
      'No boring centered stock photos with zero personality',
    ],
  },
  PRODUCT_COMMERCE_HERO: {
    id: 'PRODUCT_COMMERCE_HERO',
    name: 'Product Commerce Hero',
    description: 'Disciplined, conversion-focused commercial product advertising where the physical product/material is unmistakably dominant, sharp, and primary.',
    composition: {
      grid: 'Product-first commercial layout with hero product occupying 40-55% of canvas area',
      focalPoint: 'Dominant hero product in crisp foreground with 100% silhouette preservation',
      productScale: 'Hero product occupies 40-55% of canvas height/width, clearly readable and central',
      productPosition: 'Foreground hero position resting cleanly on relevant surface with authentic contact shadows',
      humanPosition: 'Optional: Secondary human interaction showing scale/utility without occluding product geometry or competing for visual dominance',
      negativeSpace: 'Dedicated 30-35% text-safe zones at top and bottom for bold headline, offer, and CTA',
      cropStrategy: 'Unobstructed full product envelope preserved; no extreme cropping that hides core product parts',
      cameraAngle: 'Frontal or dynamic 3/4 commercial studio angle (10-20 degrees elevation) maximizing product recognition',
      depthLayers: ['Sharp crisp foreground hero product', 'Crisp text-safe graphic overlay zones', 'Soft-focus environmental context in secondary depth', 'Atmospheric subtle background'],
    },
    artDirection: {
      visualLanguage: 'Premium commercial product photography with direct advertising conversion clarity',
      materialLanguage: 'Authentic product textures (metal, plastic, glass, fabric, masonry) with crisp tactile fidelity',
      lighting: 'Commercial studio rim lighting with controlled specular highlights, strong edge separation, and soft ambient fill',
      backgroundTreatment: 'Authentic sector environment kept secondary and softly defocused to keep product dominant',
      colorTreatment: 'True-to-life product color reproduction accented by harmonious brand tones',
      contrastStrategy: 'Strong foreground-to-background contrast making the hero product instantly pop on mobile screens',
      texture: 'High-definition physical material details with zero AI smudging or plastic artificiality',
      atmosphere: 'Professional, trustworthy, premium retail/commercial advertising caliber',
    },
    graphicLanguage: {
      shapes: ['Clean rectangular promotional cards', 'Refined pill badges for key offer/price'],
      frames: ['Discipline-driven layout bounds with clear padding'],
      lines: ['Subtle hairline separators for price and benefit clarity'],
      panels: ['High-contrast frosted or solid backing cards for maximum mobile text legibility'],
      glow: 'Controlled edge illumination separating product from background; zero cheesy neon disco glows',
      grain: 'Clean crisp commercial sharpness with subtle photographic texture',
      decorativeMotifs: ['Minimalist verification checkmark', 'Clear price and discount badges'],
    },
    typographyDirection: {
      headlineCharacter: 'Bold, punchy, high-impact commercial sans-serif display type',
      hierarchy: '1 dominant commercial headline, 1 concise offer/price callout, 1 prominent action CTA',
      alignment: 'Top or bottom aligned in high-contrast text-safe zone with generous margins',
      density: 'Mobile-first scannable in under 1 second; zero paragraph clutter',
      styleFeel: 'Apple / Nike / high-end B2B catalog commercial advertising clarity',
    },
    bestForObjectives: ['PRODUCT_INTRO', 'SALES_OFFER', 'NEW_PRODUCT', 'PRODUCT_HERO', 'CAMPAIGN'],
    antiGenericRules: [
      'Product must never become a small background prop or worn backpack hidden behind a large person',
      'No human-dominant framing where a model steals the camera from the product',
      'No cinematic landscape where nature or scenery dominates over the physical product',
      'No invented buttons, handles, hoses, nozzles, tanks, or geometry changes on the product',
      'No cluttering with excessive badges, stickers, or fake decorative text blocks',
    ],
  },
  HYBRID_PRODUCT_USAGE: {
    id: 'HYBRID_PRODUCT_USAGE',
    name: 'Hybrid Product Usage',
    description: 'Commercial product hero shown with authentic working action cues while keeping the product as the undisputed primary subject.',
    composition: {
      grid: 'Action-assisted commercial layout where product commands 40-50% foreground prominence',
      focalPoint: 'The physical product in active use with function cues (spray mist, placement, active operation)',
      productScale: 'Hero product occupies 40-50% of the active visual frame',
      productPosition: 'Foreground hero position showing active functional deployment',
      humanPosition: 'Secondary human operator (hands or cropped profile) supporting the product, never dominating',
      negativeSpace: 'Top/bottom text safe zones preserved with clean contrast for headline and offer',
      cropStrategy: 'Product body and operational connection clearly visible without occlusion',
      cameraAngle: 'Action-level 3/4 commercial angle capturing both the product and its spray/working effect',
      depthLayers: ['Sharp hero product and working stream', 'Secondary operator in subtle support', 'Environmental working backdrop in soft blur'],
    },
    artDirection: {
      visualLanguage: 'High-utility commercial demonstration with advertising polish',
      materialLanguage: 'Real working materials, functional surfaces, crisp water/mist dynamics',
      lighting: 'Directional sunlight or commercial outdoor rim light highlighting product contours and active spray',
      backgroundTreatment: 'Relevant field, garden, or workshop setting kept softly blurred in background',
      colorTreatment: 'Vibrant natural colors keeping the product color true and prominent',
      contrastStrategy: 'Crisp subject-to-background separation ensuring rapid mobile comprehension',
      texture: 'Crisp water droplets, realistic spray atomization, authentic tool materials',
      atmosphere: 'Efficient, powerful, reliable, professional equipment in action',
    },
    graphicLanguage: {
      shapes: ['Bold price pills', 'Benefit callout chips'],
      frames: ['Clean commercial margin bounds'],
      lines: ['Directional accent cues'],
      panels: ['High-contrast backing cards for pricing and CTA'],
      glow: 'Natural rim lighting on mist and product silhouette',
      grain: 'Crisp high-speed commercial photography aesthetic',
      decorativeMotifs: ['Product spec highlights', 'Official warranty badge'],
    },
    typographyDirection: {
      headlineCharacter: 'Strong, energetic, legible commercial sans-serif',
      hierarchy: 'Direct functional benefit headline, clear price/discount callout, bold CTA button',
      alignment: 'Top third or bottom third text safe zone',
      density: 'Disciplined promotional clarity with zero reading friction',
      styleFeel: 'Stihl / DeWalt / Bosch professional tool commercial campaign',
    },
    bestForObjectives: ['PRODUCT_INTRO', 'SALES_OFFER', 'REAL_USAGE'],
    antiGenericRules: [
      'Person must never cover or steal focus from the equipment',
      'Product must be clearly readable, not just seen from the back as generic baggage',
      'No fake stock photo models smiling at camera instead of operating equipment',
    ],
  },
  MATERIAL_COMMERCE_HERO: {
    id: 'MATERIAL_COMMERCE_HERO',
    name: 'Material Commerce Hero',
    description: 'Tactile, architectural material advertising where raw physical material, texture, and geometry dominate the foreground.',
    composition: {
      grid: 'Material-first commercial layout with the canonical product occupying 40-50% of visual canvas',
      focalPoint: 'Hero building material / unit placed dominantly in the crisp foreground',
      productScale: 'Material unit occupies 40-50% of canvas height/width with full form readable',
      productPosition: 'Prominently grounded on authentic architectural plinth or construction surface',
      humanPosition: 'Optional: Secondary architect or engineer in distant background context, never stealing focal weight',
      negativeSpace: 'Dedicated 30-35% negative space for refined architectural headline, specs, and CTA',
      cropStrategy: 'Full unit geometry and hole/surface patterns preserved with sharp perspective',
      cameraAngle: 'Isometric or dynamic 30-degree perspective showcasing top, front, and side textures',
      depthLayers: ['Ultra-sharp hero material with readable tactile micro-texture', 'Grounded surface with authentic contact shadow', 'Secondary architectural scaffolding or modern structure', 'Distant sky/cityscape backdrop'],
    },
    artDirection: {
      visualLanguage: 'Architectural materiality, monumental craftsmanship, industrial durability',
      materialLanguage: 'Natural kiln-fired clay, porous terracotta, honed stone, raw concrete, structural steel',
      lighting: 'Raking sun or architectural studio light revealing tactile surface ridges and hole depths',
      backgroundTreatment: 'Modern construction site or finished architectural facade kept softly in the background',
      colorTreatment: 'Earthy terracotta, warm brick clay, and mineral tones balanced with neutral architectural grays',
      contrastStrategy: 'Rich tactile micro-contrast across clay textures and deep shadow cavities in perforations',
      texture: 'Authentic kiln-fired roughness, grooved extrusion ridges, and natural mineral specks',
      atmosphere: 'Permanent, engineered, structural, premium architectural grade',
    },
    graphicLanguage: {
      shapes: ['Architectural hairline grids', 'Minimalist spec cards'],
      frames: ['Slender 1px borders inspired by architectural blueprints'],
      lines: ['Fine dimension/specification guidelines'],
      panels: ['Matte mineral or charcoal backing panels for high contrast copy'],
      glow: 'Zero artificial glow; pure natural daylight specular glints',
      grain: 'Subtle stone/film texture enhancing tactile realism',
      decorativeMotifs: ['Quality certification mark', 'Durability guarantee seal'],
    },
    typographyDirection: {
      headlineCharacter: 'Architectural grotesk or refined modern grotesque display with tight tracking',
      hierarchy: 'Authoritative headline, technical spec/price line, minimalist high-contrast CTA',
      alignment: 'Flushed left with structured grid discipline',
      density: 'Clean editorial-commercial balance; highly readable on mobile',
      styleFeel: 'Wienerberger / Swiss architectural product catalog / high-end facade advertising',
    },
    bestForObjectives: ['BRAND_AWARENESS', 'PRODUCT_HERO', 'PREMIUM'],
    antiGenericRules: [
      'The material must never become a tiny prop placed on a distant table',
      'No worker dominating the camera over the material product',
      'No altered hole count or fantasy brick geometry; canonical reference is absolute law',
      'No soft cartoonish rendering; surface must feel physically heavy and tactile',
    ],
  },
}

export function getArchetype(id: string): ArchetypeGrammar {
  return CREATIVE_ARCHETYPES[id] || CREATIVE_ARCHETYPES.CINEMATIC_PRODUCT_HERO
}

export function listArchetypeIds(): string[] {
  return Object.keys(CREATIVE_ARCHETYPES)
}
