'use client';
import {useState,useEffect,useId,useRef} from 'react';
import {AudienceRequest} from './campaign-control-center';
import {MesajifyMark} from '../brand/mesajify-mark';
export function AudienceWorkspace({onReady}:{onReady:(ready:boolean)=>void}) {
 const [mode,setMode]=useState<'upload'|'request'>('upload'),[checked,setChecked]=useState(false);const id=useId();
 const [scanned,setScanned]=useState(0),[checking,setChecking]=useState(false);const ref=useRef<HTMLDivElement>(null);const autoStarted=useRef(false);const manual=useRef(false);
 useEffect(()=>{const node=ref.current;if(!node)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting&&!autoStarted.current){autoStarted.current=true;setChecking(true)}},{threshold:.2});observer.observe(node);return()=>observer.disconnect()},[]);
 useEffect(()=>{if(!checking)return;let timer;const tick=()=>{const node=ref.current;if(!node||node.getBoundingClientRect().bottom<=0||node.getBoundingClientRect().top>=innerHeight||document.hidden||node.closest('[data-story-paused]')?.getAttribute('data-story-paused')==='true')return;setScanned(value=>Math.min(4,value+1))};const media=matchMedia('(prefers-reduced-motion: reduce)');if(media.matches){setScanned(4);return}timer=setInterval(tick,500);return()=>clearInterval(timer)},[checking]);
 useEffect(()=>{if(scanned===4){setChecked(true);setChecking(false)}},[scanned]);
 useEffect(()=>{if(!checked||mode!=='upload'||manual.current||matchMedia('(prefers-reduced-motion: reduce)').matches)return;let elapsed=0;const timer=setInterval(()=>{const node=ref.current;if(!node||document.hidden||node.closest('[data-story-paused]')?.getAttribute('data-story-paused')==='true'||node.getBoundingClientRect().bottom<=0||node.getBoundingClientRect().top>=innerHeight)return;elapsed+=500;if(elapsed>=4500){setScanned(0);setChecked(false);setChecking(true)}},500);return()=>clearInterval(timer)},[checked,mode]);
 const ready=mode==='upload'&&checked;
 useEffect(()=>{onReady(ready)},[ready,onReady]);
 return <div ref={ref} className="ml-audience-workspace" data-checking={checking}><header><MesajifyMark size="md" decorative/><div><h3>Tanıtım kitlesi</h3><p>Listenizi hazırlayın, tanıtımınıza dahil edin.</p></div><span>Örnek akış</span></header>
 <ol className="ml-audience-steps" aria-label="Kitle hazırlama adımları">{['Kitle','Kontrol','Tanıtıma hazır'].map((label,i)=><li key={label} data-active={i===(ready?2:mode==='request'?1:0)} data-complete={ready&&i<2}><span>{ready&&i<2?'✓':i+1}</span>{label}</li>)}</ol>
 <div className="ml-audience-methods" role="tablist" aria-label="Kitle hazırlama yöntemi">{[['upload','Müşteri Rehberim','Kayıtlı müşterileriniz'],['request','Bölge & Sektör','Hedef kitle belirleyin']].map(([key,label,note])=><button key={key} role="tab" id={id+'-'+key} aria-controls={id+'-panel'} aria-selected={mode===key} tabIndex={mode===key?0:-1} onClick={()=>{manual.current=true;setChecking(false);setMode(key as 'upload'|'request')}} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();manual.current=true;setChecking(false);const next=e.key==='Home'?'upload':e.key==='End'?'request':mode==='upload'?'request':'upload';setMode(next);document.getElementById(id+'-'+next)?.focus();}}}><strong>{label}</strong><small>{note}</small><span>{mode===key?'●':'○'}</span></button>)}</div>
 <div role="tabpanel" id={id+'-panel'} aria-labelledby={id+'-'+mode} className="ml-audience-content">{mode==='upload'?<><div className="ml-audience-file"><svg viewBox="0 0 40 48" aria-hidden="true"><path d="M6 2h18l10 10v34H6zM24 2v12h10M12 24h16M12 31h16M20 20v18" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg><div><strong>Müşteri Rehberi</strong><small>Kayıtlı numaralarınız · Otomatik düzenleme</small></div><button onClick={()=>{manual.current=true;setScanned(0);setChecked(false);setChecking(!checked)}} disabled={checking}>{checking?'Kontrol ediliyor…':checked?'Yeniden Kontrol Et':'Listeyi Kontrol Et'}</button></div><div className="ml-audience-table"><div className="ml-audience-table-head"><span>Kayıt</span><span>Kontrol durumu</span></div>{[0,1,2,3].map(i=><div className="ml-audience-record" data-scanned={scanned>i} key={i}><span><i>{String(i+1).padStart(2,'0')}</i>Örnek müşteri {i+1}</span><small data-excluded={scanned>i&&i===2}>{scanned>i?i===2?'Hariç tutuldu':i===1?'Kontrol edildi':'Hazır':'Kontrol bekliyor'}</small></div>)}</div></>:<AudienceRequest/>}</div>
 <div className="ml-audience-notice" key={scanned}><span>{checked?"✓":"↥"}</span><div><small>LİSTE KONTROLÜ · ÖRNEK</small><strong>{mode==="request"?"Sektör ve bölge tercihlerinizi belirleyin":checked?"3 kayıt tanıtım listesine eklendi":scanned?`Örnek kişi ${scanned} · ${scanned===3?"hariç tutuldu":"kontrol edildi"}`:"Liste kontrol için hazırlanıyor"}</strong></div></div><footer className="ml-audience-result" data-ready={ready}><span>{ready?'✓':'○'}</span><div><strong>{ready?'Tanıtım kitlesi hazır':mode==='request'?'Talep → değerlendirme → kitle hazırlığı':'Liste kontrolünden sonra tanıtıma hazır'}</strong><p>{ready?'3 örnek kayıt tanıtım listesine dahil edildi.':mode==='request'?'Talep edilen liste, değerlendirme ve hazırlık tamamlandığında tanıtıma dahil edilir.':'Hariç tutulan örnek kayıt tanıtım listesine dahil edilmez.'}</p></div></footer>
 <p className="ml-audience-preview-note">Arayüz gösterimi · gerçek liste yüklenmez, talep veya gönderim yapılmaz.</p></div>;
}
