'use client';
import {useState,useEffect,useRef,useId} from 'react';
import {GeneratedMediaSlot} from './generated-media-slot';
import {MesajifyMark} from '../brand/mesajify-mark';
import {AnimatedInboxSvg} from './animated-inbox-svg';
import {replyExamples} from './story-messages';
const steps=['Marka & ürün','Kreatif','Kitle','Tanıtım','Ortak Inbox'];
const descriptions=['Marka kiti ve seçili ürün, kreatifin başlangıç noktası.','Ürün fotoğrafından tanıtım görseline ve dikey videoya.','Kendi listenizi hazırlayın veya değerlendirme için liste talep edin.','Tanıtımınız seçili kitleye, bağlı WhatsApp hatları üzerinden ilerler.','Farklı hatlardan gelen yanıtları aynı Gelen Kutusu’nda takip edin.'];
const outcomes=['Marka kiti ürüne bağlandı','Tanıtım kreatifi seçildi','Kontrol edilen liste hazır','Seçili hatlar tanıtıma bağlandı','Yanıt ortak Gelen Kutusu’nda'];
export function CampaignScene(){const [active,setActive]=useState(0);const [round,setRound]=useState(0);const [playing,setPlaying]=useState(true);const [visible,setVisible]=useState(false);const [reduced,setReduced]=useState(false);const ref=useRef<HTMLDivElement>(null);const id=useId();
useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>setReduced(media.matches);sync();media.addEventListener('change',sync);return()=>media.removeEventListener('change',sync)},[]);
useEffect(()=>{const node=ref.current;if(!node)return;let inView=false;const sync=()=>setVisible(inView&&!document.hidden&&document.documentElement.dataset.labPaused!=='true');const observer=new IntersectionObserver(([entry])=>{inView=entry.isIntersecting;sync()},{threshold:.01});observer.observe(node);document.addEventListener('visibilitychange',sync);window.addEventListener('lab-motion-change',sync);return()=>{observer.disconnect();document.removeEventListener('visibilitychange',sync);window.removeEventListener('lab-motion-change',sync)}},[]);
useEffect(()=>{if(!playing||!visible||reduced)return;const timer=window.setTimeout(()=>{if(active===4)setRound(value=>value+1);setActive((active+1)%5)},active===4?3200:1600);return()=>window.clearTimeout(timer)},[playing,visible,reduced,active]);
const select=(next:number)=>{setPlaying(false);setActive(next)};
useEffect(()=>{window.dispatchEvent(new Event('lab-motion-change'))},[playing]);
return <div ref={ref} className="ml-campaign-scene" data-story-paused={!playing} data-focus={active} data-playing={playing&&visible&&!reduced} data-running={visible&&!reduced}><div className="ml-scene-tabs" role="tablist" aria-label="Tanıtım hikâyesi">{steps.map((s,i)=><button key={s} id={id+'-'+i} aria-controls={id+'-description'} role="tab" aria-selected={active===i} tabIndex={active===i?0:-1} onClick={()=>select(i)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?4:(active+(e.key==='ArrowRight'?1:4))%5;select(next);document.getElementById(id+'-'+next)?.focus()}}}><span>0{i+1}</span>{s}</button>)}</div>
<div className="ml-scene-description" id={id+'-description'} role="tabpanel" aria-labelledby={id+'-'+active} aria-live={playing?'off':'polite'}><div className="ml-scene-summary"><span>{steps[active]}</span><p>{descriptions[active]}</p></div><button className="ml-scene-play" onClick={()=>{if(playing){setPlaying(false)}else{setActive(0);setPlaying(!reduced)}}} disabled={reduced} aria-label={playing?"Akışı duraklat":"Örnek akışı oynat"}>{playing?"Ⅱ Duraklat":"▷ Akışı izle"}</button></div><div className="ml-scene-feedback" key={active}><span className="ml-scene-feedback-icon">✓</span><span><small>ÖRNEK AKIŞ · 0{active+1} / 05</small>{outcomes[active]}</span><span className="ml-scene-feedback-progress" aria-hidden="true"><i/></span></div>
<div className="ml-scene-canvas"><svg className="ml-scene-wires" viewBox="0 0 1200 720" preserveAspectRatio="none" aria-hidden="true">{['M220 220 C330 220 360 220 460 220','M740 220 C850 220 860 220 980 220','M1010 380 C1010 475 200 370 200 490','M340 600 C490 600 540 600 650 600','M690 600 C820 600 840 600 950 600'].map((d,i)=><g key={d}><path d={d} fill="none" stroke="#bfd3c5" strokeWidth="1.5"/><path key={active+"-"+i} d={d} pathLength="100" className="ml-scene-signal" data-selected={active===i} fill="none" stroke="#00a884" strokeWidth="4" strokeLinecap="round"/></g>)}</svg>
<div className="ml-scene-top"><article className="ml-scene-node ml-scene-brand" data-selected={active===0}><span className="ml-object-label">MARKA + ÜRÜN</span><div className="ml-scene-brand-title"><strong>Mesajify</strong><span>Marka kiti ✓</span></div><div className="ml-scene-product"><img src="/brand/mesajify-official-logo.png" alt="Mesajify WhatsApp Tanıtım Platformu" loading="lazy" style={{padding:'12px',objectFit:'contain'}}/></div><div className="ml-scene-swatches" aria-label="Mesajify marka renkleri"><i style={{background:'#00A884'}}/><i style={{background:'#168347'}}/><i style={{background:'#07100C'}}/><span>Mesajify marka kiti · aktif</span></div><p>WhatsApp Tanıtım & Kitle</p></article>
<div className="ml-scene-creative" data-selected={active===1}><div className="ml-scene-media-header"><MesajifyMark size="sm" decorative/><span>TANITIM KREATİFİ</span></div><GeneratedMediaSlot id="real-product-video" alt="Mesajify dikey tanıtım videosu"/><div className="ml-scene-media-footer"><span>Dikey Tanıtım</span><small>Veo 3.1 video · 9:16</small></div></div>
<article className="ml-scene-node ml-scene-audience" data-selected={active===2}><span className="ml-object-label">TANITIM KİTLESİ</span><h3>Doğru kitleyle başlayın.</h3><div><span>↥</span><strong>Liste yükle</strong><small>Excel / CSV → kontrol</small></div><div><span>↗</span><strong>İşletme bulucu</strong><small>Sektör / bölge taraması</small></div><p>Doğrulanmış WhatsApp numaraları doğrudan tanıtım listenize eklenir.</p></article></div>
<div className="ml-scene-bottom"><article className="ml-scene-node ml-scene-launch" data-selected={active===3}><MesajifyMark size="lg" decorative/><h3>Doğrudan tanıtım.<br/>Güvenli gönderim.</h3><div className="ml-scene-line-cards">{[1,2,3].map(i=><span key={i}><i/>Hat 0{i}<small>Bağlı</small><b aria-hidden="true">↗</b></span>)}</div><small>Otomatik dağıtım · kontrollü gönderim</small></article><div className="ml-scene-message" key={round+"-reply"}><div className="ml-scene-chat-header"><span className="ml-scene-avatar">A</span><span>Örnek müşteri<small>WhatsApp üzerinden yanıt</small></span><i/></div><div className="ml-scene-chat-body"><div className="ml-scene-chat-ad"><span>MESAJIFY</span><strong>WhatsApp Tanıtım Platformu</strong><small>Tanıtım kreatifi paylaşıldı <span>✓✓</span></small></div><div className="ml-scene-chat-reply">{replyExamples[round%replyExamples.length]}<small>Şimdi</small></div><div className="ml-scene-chat-result"><span>✓</span>Yanıt Gelen Kutusu’na ulaştı</div></div><small>Örnek konuşma · gerçek zamanlı gelen kutusu</small></div><article className="ml-scene-node ml-scene-inbox" data-selected={active===4}><span className="ml-object-label">ORTAK GELEN KUTUSU</span><AnimatedInboxSvg paused={!playing}/><p>Gelen sipariş ve talepler tek ekranda</p></article></div></div><p className="ml-scene-note">Mesajify tanıtımı · örnek akış. Aşamaları seçerek keşfedin.</p></div>}

